### ISSUE TITLE
Powermax Pro HA integration

### ISSUE THREAD

**Issue by massimo79** [davesmeghead/visonic#1]
HY! This is amazing...I am new to HA so I need to start at the very beginning (sorry about this!).
What to I need to get this started? I have a Powermax Pro without RS232 or Powerlink..what do you suggest to buy? Ps: just in case, is the Powerlink 3 suitable? (i doubt I can find a PL2 anymore).

Thanks, keep up the great job

**Comment by davesmeghead** [comment]
Hi,
Starting at the beginning is OK, we all have to learn and I don't mind helping anyone.

I bought this:
[https://www.aliexpress.com/item/USR-TCP232-E-Serial-Server-RS232-RS485-To-Ethernet-TTL-Level-DHCP-Web-Module/32687581169.html](url)

There is a wifi version available that's a bit more expensive. 

You do not need to buy anything else apart from 4 wires. You connect it in to your Visonic alarm panel like this
[https://www.domoticaforum.eu/viewtopic.php?f=68&t=7152](url)

I connected the 3.75v pin on the panel to the Vcc on this device, gnd to gnd and Tx to Rx, Rx to Tx. 4 wires and that's it.

This allows you to connect your alarm panel directly to your ethernet network. There is a webserver running on this and you need to set it up for TCP in STA (station) mode as transparent. The RS232 side is 9600 baud, disable control flow i.e CTS/RTS, no parity and 1 stop bit. In my visonic HA plugin you set the ip address and port for this device.

That's it!
Best Regards and Good Luck

**Comment by Mjohannesson** [comment]
Brilliant,  I have been teaching myself python while attempting to extract sensor states and system status from my PowerMax Pro via the PowerLink interface.  

Have you run this against a PowerLink module (the docs talk about getting it in PowerLink mode) or just with the serial to ethernet converters?

I can consistently log in and get the information (XML converted to python objects) but eventually lose my mind with the variability of the data.  I like your search approach and will see if i can make some headway there.

The HA side is likely beyond my skills at this point so it is awesome to see the work you have done so far!

Thanks
Mark

**Comment by davesmeghead** [comment]
I'm sorry but I don't think it will work with the Powerlink module. It works with either a USB to TTL RS232 or Ethernet to TTL RS232 modules. I think that the powerlink module has it's own web interface inside it but I'm not sure.
