### ISSUE TITLE
triggering alarm panel service (Arm_ disarm etc) Not working in script/automation as of 2024.1

### ISSUE THREAD

**Issue by bartbakels** [davesmeghead/visonic#102]
Not sure if this is an visonic integration issue, but i have a very strange issue. I have scripts to arm and disarm which were not working. 

created clean script and automation tried send command service, Alarmpanel disarm service etc. All are working when triggering the action manually, but when running the script of automation nothing happens (no disarm or arming) but there are also no errors in the log. So triggering actions manually it works as expected but when triggering the autpomations manually or by trigger its not arming/disarming.

Anybody else experience this error?

**Comment by EyalRotem** [comment]
I haven’t. But it may be wise to upload your script/automation.

I use the disarm service in an automation, it looks like this:
`service: alarm_control_panel.alarm_disarm
data: {}
target:
    entity_id: alarm_control_panel.visonic_alarm_panel
`

and works as expected.

**Comment by bartbakels** [comment]
Are you using 2024.1.2?

the scripts are very simple

**Comment by bartbakels** [comment]
yes, the traces dont show any issues either, so thats the strange thing. triggereing the action manually in the script is working as expected, running the script , is not working. so this sounds like an core issue

**Comment by bartbakels** [comment]
one thing, you are not using a pincode, maybe that is not interpreted. let me test that theory

**Comment by bartbakels** [comment]
Got it, i disabled 
'Force use of a Numeric Keypad' 


and now it is working.... so it seems that it has something todo with the pincode usage?

**Comment by EyalRotem** [comment]
Could be, I have mine inside home assistant and I don’t input it ever.

**Comment by bartbakels** [comment]
it looks like the data  of the service call is not processed

**Comment by davesmeghead** [comment]
Hi, 
Can you Enable Debug Logging for the Integration, do what you're trying to do and then Disable Debug Logging.  When you disable then you'll get a log file downloaded in your browser.  Upload (or copy/paste) the relevant part of the log file here please.

**Comment by mycanaletto** [comment]
> Got it, i disabled 'Force use of a Numeric Keypad'
> and now it is working.... so it seems that it has something todo with the pincode usage?

Same thing, I had to disable this option even though I hadn't changed the configuration for over a year....

**Comment by mycanaletto** [comment]
I deactivated it, so I no longer have the keyboard displayed in Lovelace and it works with or without a code... It would be nice to understand what has happened since 2024.1 ....

**Comment by davesmeghead** [comment]
> It would be nice to understand what has happened since 2024.1

As I said, please provide me with a debug log fie......

> Can you Enable Debug Logging for the Integration, do what you're trying to do and then Disable Debug Logging. When you disable then you'll get a log file downloaded in your browser. Upload (or copy/paste) the relevant part of the log file here please.

**Comment by bartbakels** [comment]
This issue seems to be resolved, not sure as of which version. But it is working again, for me
