### ISSUE TITLE
powermaster 10 - cannot get a connection via powerlink 3.1

### ISSUE THREAD

**Issue by apfi23120616** [davesmeghead/visonic#107]
hello Davesmeghead
i have a powermaster 10 and i cannot get a connection via powerlink 3.1. is it supported?
i enter the ip address of the powerlink device provided by the router on my network and port 30000.
is this the correct procedure? 
is it possible to have a step by step guide for the ethernet connection?
thank you very much

**Comment by EyalRotem** [comment]
There is a whole [wiki](https://github.com/davesmeghead/visonic/wiki).
Have you trying earring there?

it doesn’t support the PowerLink module, the integration is sort of emulating it.
See the wiki for options. I use an esp device and it works flawlessly and fast.

**Comment by apfi23120616** [comment]
yes I read it and in the wiki a powerlink method is mentioned, so I meant that it was now supported
Now I understand and I will try to use your method with ESP device. 
thank you very much

**Comment by davesmeghead** [comment]
Hi, I'll close this as an issue as it isn't really an ongoing issue, further problems then create a new issue for that specific problem
