### ISSUE TITLE
Error on Powermx Pro panel "“BBA com lost"

### ISSUE THREAD

**Issue by vdiogo** [davesmeghead/visonic#109]
I have been using this integration since 3 months but since 3 days back I get daily errors on my Powermac Pro panel as "“BBA com lost”.

The only error (warnings) I can find in home assistant logs are:
```
Logger: custom_components.visonic.client
Origem: custom_components/visonic/client.py:203
integração: Visonic Intruder Alarm ([documentação](https://github.com/davesmeghead/visonic/wiki), [problemas](https://github.com/davesmeghead/visonic/issues))
Primeira ocorrência: 12 de abril de 2024 às 11:42:38 (83 ocorrências)
Último registo: 06:13:12

Warning: Valid 4 digit PIN not found, panelmode is 1
```

and 
```
Logger: custom_components.visonic.pyvisonic
Origem: custom_components/visonic/pyvisonic.py:1633
integração: Visonic Intruder Alarm ([documentação](https://github.com/davesmeghead/visonic/wiki), [problemas](https://github.com/davesmeghead/visonic/issues))
Primeira ocorrência: 12 de abril de 2024 às 11:46:56 (9 ocorrências)
Último registo: 13 de abril de 2024 às 06:35:42

[_sendMsgENROLL] Warning: Trying to re enroll, already tried DFFD and still not successful
```

Which don't seem related (AFAIK) with the above.

The manual suggest that when these type of issues occur to enter/exit the installation mode on powermax which I have just done. Maybe opening/closing the panel may help.

Any suggestion would be welcomed

**Comment by davesmeghead** [comment]
Hi, set the logger to debug as per the wiki [here](https://github.com/davesmeghead/visonic/wiki#logger-settings) and upload the Home Assistant Log file in this issue and I'll take a look.
Do you connect using Ethernet?  If so have you changed anything that could affect the connection?

**Comment by vdiogo** [comment]
> Hi, set the logger to debug as per the wiki [here](https://github.com/davesmeghead/visonic/wiki#logger-settings) and upload the Home Assistant Log file in this issue and I'll take a look. Do you connect using Ethernet? If so have you changed anything that could affect the connection?

Thanks for prompt reply! Logger ON.
I connect with WiFi. No changes in the last months

**Comment by davesmeghead** [comment]
I should have mentioned, after changing the logger settings please remember to then restart Home Assistant

**Comment by vdiogo** [comment]
@davesmeghead I'll close this issue as I haven't observed the issue since some days. I'm assuming enter/exit the installation mode helped here.
