### ISSUE TITLE
custom integration 'visonic' accesses hass.helpers.service. This is deprecated

### ISSUE THREAD

**Issue by haforme** [davesmeghead/visonic#110]
Upgraded to HA version 2024.5.1 and received following error message.

Detected that custom integration 'visonic' accesses hass.helpers.service. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from service directly at custom_components/visonic/__init__.py, line 232: hass.helpers.service.async_register_admin_service(, please create a bug report at https://github.com/davesmeghead/visonic/issues

**Comment by rogerthn2019** [comment]
Running 2024.5.2

> WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'visonic' accesses hass.helpers.service. This is deprecated and will stop working in Home Assistant 2024.11 ...

**Comment by davesmeghead** [comment]
I've fixed this in the dev release and I'm confident that it will be in the master release by November 2024

**Comment by davesmeghead** [comment]
I've pulled the Dev to the Master so I'll close this Issue
