### ISSUE TITLE
Triggering alarm/sounding siren (feature request)

### ISSUE THREAD

**Issue by mlstolk** [davesmeghead/visonic#111]
Would it be possible to add the functionality to trigger an alarm from this integration?
Preferably with the type, such as zone violation, fire, panic or maybe linked to one of the zones of the panel.

This would help in sounding the siren and/or getting a phone call from the panel when a HA sensor (smoke sensor, PIR/contact, flood sensor, etc. is triggered).

**Comment by davesmeghead** [comment]
Hi,
I've already added this to the dev build and a few people are trying it already. 
It only works with PowerMaster Panels and has only been confirmed to work on PowerMaster 30.

As far as I know there is no way to do this for PowerMax Panels.

If you have a PowerMaster panel and are able to unzip the dev build then give it a try

Dave

**Comment by mlstolk** [comment]
Ah, great to hear from a development perspective. Unfortunately I do have a Powemax Complete, so I will have to look into another way (e.g. wiring into a transmitter).
If it does become possible in the future than I'm highly interested!
Martin

**Comment by davesmeghead** [comment]
You could potentially use the ESPHome build [here in the wiki](https://github.com/davesmeghead/visonic/wiki/Using-Wemos-and-ESPHome#using-wemos-d1-r2-and-you-can-trigger-the-siren) and use a relay to trigger a wired input on your panel, assuming that you have wired inputs to use.
