### ISSUE TITLE
I don't know how to connect to the Visonic Alarm Panel

### ISSUE THREAD

**Issue by sdmorris1950** [davesmeghead/visonic#115]
A few months ago I asked about connecting to me Visonic alarm (Issue #104) and davesmeghead told me to get a USR-TCP232-E2, which I did, and how to wire it up with Dupont wires.
I just got around to trying to connect it and I don't see where.
![20240603_101245](https://github.com/davesmeghead/visonic/assets/15718404/55e50e2f-391e-475a-a387-597b499d6837)
![20240603_101305](https://github.com/davesmeghead/visonic/assets/15718404/c94c685a-cc64-49ff-af4e-f9cc34dc5d5c)
![20240603_103611](https://github.com/davesmeghead/visonic/assets/15718404/ef789a3f-0686-4568-8a18-81047ff89dde)
![20240603_103618](https://github.com/davesmeghead/visonic/assets/15718404/e5a5a155-2498-4e52-9b61-4ee592157c7d)
![20240603_103638](https://github.com/davesmeghead/visonic/assets/15718404/2958bf43-7640-4b35-ac7c-671905df984f)

I assumed that it would be to the PowerMaster-10, but I do not see where. 
I then looked in the Force 32 board, and it has a connector for RS-232, but no pin-out. There also appears to be an unused Ethernet port.

I have attached photos of the inside of the PowerMaster-10 and of the Force 32 board.

**Comment by davesmeghead** [comment]
Hi,
Sorry for any confusion but you can't use this integration with a PowerLink 3 hardware device.
The 10 way ribbon cable uses the connector that you need.
Dave

**Comment by sdmorris1950** [comment]
I don't understand.
In your previous emails, you wrote that I couldn't use a Powerlink 3
hardware module, but that I could connect with either the USR-TCP232-E2
module or the Wemos D1 R2 module..

Are you now saying that there is no way for me to connect to HA?

Steve

**Comment by davesmeghead** [comment]
It looks like you currently have a powerlink 3 module from your last photo. Disconnect to 10 way ribbon cable from the panel, use that panel connector to connect the USR device as per the wiki.
You can either use the USR or rhe powerlink hardware but not both at the same time, although I'm working on this
Dave

**Comment by sdmorris1950** [comment]
Unfortunately, not an option. My alarm system is connected to my Home
Security service via the powerlink 3 module.

Please let me know when you have a version that supports both. I would be
happy to beta test it. Any estimate of when that might be?

Steve

**Comment by davesmeghead** [comment]
Hi,

**Force 32**
I'm intrigued by your use of both a PM10 and a PIMA Force Series 32 alarm system at the same time.  Can you explain a bit more abut your setup.  
The Force 32 is an alarm system in itself and doesn't need a PM10. What wires go between the Force 32 board and the PM10?

This is the manual for the Force32 board that you have:
[Force-User-XX-en-B3-Dec-2019.pdf](https://github.com/user-attachments/files/15753115/Force-User-XX-en-B3-Dec-2019.pdf)

It may be obvious but this integration does not support the Force 32 board, only the PM10 functionality.

**And now on to the "Bridge"**
I have just created a Github alpha release [here](https://github.com/davesmeghead/visonic_esp32_bridge) for the ESPHOME yaml configuration file.

Most of the things you'll need to know are on there. The important things for you are:
- I'm sorry but you'll need to buy some hardware. An ESP32 hardware device, cost is around £10 each including delivery.  The USR-TCP232-E2 is not programmable and so can't be used as a bridge.
- Follow some fairly simple instructions to wire it in using dupont cables, not currently on the github but I'll add it soon
- Have a working ESPHOME system set up, see [here](https://esphome.io/)
- Be able to spend some time testing it but initially not connected to Home Assistant.  Initially the testing is to make sure that the system works as it does now.

Dave

**Comment by sdmorris1950** [comment]
My alarm system is connected to the local security firm, and they installed the system and maintain it. I hadn't really looked at it in detail until my attempts to connect it to HA, and I hadn't taken in that the Force board is from Pima.
The firm usually uses Pima systems, and my previous setup was a Pima. But after renovations, I had some requirements that they said are not supported by Pima and replaced it with the Powermaster 10. In fact, the purchase order only has the Powermaster 10, the POWERLINK-3 and about 20 Powermaster wireless motion sensors and magnets. 
After your comments last week, I asked the technician, and he explained that the POWERLINK-3 gives me the internet link. That gives the security firm visibilty to the system and I use it to connect from the phone app.
The only thing he said about the Force board is that it has a SIM and provides the cellular connection to the security firm. I will have to check with the technician, but, since it does not appear on the purchase order, maybe this was a left over from my previous system.
You can see the connection between them in the attached photo. Two pairs of wires go from the Force board to power and to the alarm on the Powermaster. Presumably that sends the alarm signal to the security firm over cellular, even if the internet is down.

Coming back to your ESP32 solution, where does it connect to the Powermaster 10 and does it work alongside the POWERLINK-3?

![Screen Shot 06-09-24 at 10 04 PM](https://github.com/davesmeghead/visonic/assets/15718404/f36188ec-edb4-4701-a9a0-2b33ba42fe63)

**Comment by davesmeghead** [comment]
> Coming back to your ESP32 solution, where does it connect to the Powermaster 10 and does it work alongside the POWERLINK-3?

The end result would be to replace the 10 way grey ribbon cable between the panel and the powerlink by inserting an ESP32 device with the ESPHOME configuration on it.  Currently the panel and powerlink interact using RS232 (UART) protocols, we would be inserting the ESP32 in that path so the panel communicates with the ESP32 and then the ESP32 communicates with the powerlink, and vice-versa. 

So yes **it should work as it does now**, the ESP32 should forward on the messages to and from each of the panel and powerlink.
The advantage this gives us is that the ESP32 also has a Wifi connection to support the Integration from Home Assistant. 

Having said all of that, as you have an external security firm that monitors your system it may not be appropriate for you to experiment with this setup as you'll be interrupting that external interaction while you experiment by setting it up and trying it. 
On the one hand, the advantage for me is that this would show whether it works or not (i.e. is transparent to external companies), on the other hand you may get in trouble from that external company as it may look to them that your system has a fault and has stopped communicating, they may start contacting you and giving you grief.

Let me know what you prefer to do

Dave

**Comment by davesmeghead** [comment]
I've done a wiring diagram
![image](https://github.com/davesmeghead/visonic/assets/10319422/90626bec-8879-47f2-a465-d41bc5dc336d)

Initially you would not need the 3.75 to 3.3 convertor as the ESP32 would be powered from USB to your PC/Laptop.
The blue lines represent the Rx/Tx, notice that the ESP32 is inserted in the path between the panel and powerlink.

**Comment by sdmorris1950** [comment]
Great. The wiring diagram makes the setup much clearer. The ribbon cable is replaced by dupont wires.
I have ordered a couple of ESP32 boards and 3.3V Step-Up/Step-Down regulators from AliExpress. They will take 2–3 weeks to arrive.

**Comment by EyalRotem** [comment]
Hi Dave,
I see you got some progress on the powerlink bridge setup. the github page is helpful.
i remember sometime ago you replied to an issue with more info on how to connect everything, is there a place that consolidates all the steps?
you are so helpful, investing so much time in replying - i feel that if you could write up as you did with the current integration, it would make things simpler for us and yourself.

as always, much obliged!

**Comment by davesmeghead** [comment]
Hi and Thankyou
There's just the github page at the moment:
https://github.com/davesmeghead/visonic_esp32_bridge
Give me a few days and I'll update it with a bit more detail and a walkthrough of steps to take.  Although it's not that complex, Wire up the ESP32 device as above, configure the various settings in ESPHOME and install the configuration to the ESP32. That should bridge between the panel and the powerlink.  Once that's working we can look more at connecting Home Assistant to the Wifi connection, I currently connect in Standard Mode in my test setup as the panel does not like having 2 powerlink devices to interact with.
Anyway, in the mean time you'll need an ESP32 microcontroller and be able to install the ESPHOME config to it. Do this before you wire it in.
Dave

**Comment by sdmorris1950** [comment]
Hi Dave,
I am ready to start work on setting this up.
I have the network configuration details, except how do I find out
what the network
port is?

Thanks,
Steve

**Comment by sdmorris1950** [comment]
Oh, my misunderstanding. I thought that this is a port on the PowerMaster
but, of course, it is on the ESP32, and I can choose

**Comment by davesmeghead** [comment]
OK, let me know how you get on with it

**Comment by davesmeghead** [comment]
Closing this issue, if the problem continues then either reopen or create a new issue please
