### ISSUE TITLE
Alarm Panel Will not Arm after HA Upgrade

### ISSUE THREAD

**Issue by haforme** [davesmeghead/visonic#116]
I upgraded HA to version 2024.6.3 and the alarm panel will not Arm.  I receive the following message when I try to.

Failed to call service alarm_control_panel/alarm_arm_away. Validation error: Arming requires a code but none was given for alarm_control_panel.visonic_alarm

This link seems to explain why but not sure where statement would be applied.

https://developers.home-assistant.io/blog/2024/05/22/alarm_control_panel_validation/

As a work around I used the Developer Service "Alarm control panel: Arm away" and entered my code and the panel Armed.

**Comment by mycanaletto** [comment]
Same problem, I admit I didn't look any further because I'm not at home.

**Comment by EyalRotem** [comment]
Just to pitch in- I don’t have the issue. Using esp connected to a powermaster10.
I just use the alarm card, specifically the mushroom one. Not sure how it calls the services though.

**Comment by davesmeghead** [comment]
Have you seen this in the release notes for the latest HA Release
https://developers.home-assistant.io/blog/2024/05/22/alarm_control_panel_validation

**Comment by haforme** [comment]
Ticking what you suggested fix it. Thanks
