### ISSUE TITLE
Version 0.9.6.5 Alarm unvalaible

### ISSUE THREAD

**Issue by open1999** [davesmeghead/visonic#124]
Hello Dave,

I installed the last version.

It's not OK

System
![image](https://github.com/user-attachments/assets/780feac7-7aad-4a11-9a99-0e8ec22acacb)

Dashboard
![image](https://github.com/user-attachments/assets/23fe72bd-6670-4592-a475-a56f576e0c1b)

Log
` deleted by open1999
`

Thanks

Daniel

**Comment by open1999** [comment]
I do a new "configure"
![image](https://github.com/user-attachments/assets/a6cb3ce6-44b1-4dcf-b8bc-7063f581483c)

and I modified 

![image](https://github.com/user-attachments/assets/1b095c3c-9fc1-48e1-ac74-82c7b6dfaa0e)

It's ok

**Comment by open1999** [comment]
I've seen my version is now 9.6.4
![image](https://github.com/user-attachments/assets/80aa2217-1f43-45f9-8b3f-cdb0f83cc730)

**Comment by davesmeghead** [comment]
Is it still not OK?
If not then zip up the log file and drag the zip file in to a comment here, I can't read that log file above and I assume it's out of date as you closed and reopened the thread.

If you leave the panel number at 0 then it should not create the new alarm panel entity as `alarm_control_panel.visonic_alarm_2`

**Comment by open1999** [comment]
I leave the panel number at 0 but the update created **alarm_control_panel.visonic_alarm_2**

It's ok, it's run.

the version number displayed 0.9.6.4 instead of 0.9.6.5
![PrtScr capture_2](https://github.com/user-attachments/assets/00df44fd-9814-4a1c-8232-50b3f597a4e7)

**Comment by davesmeghead** [comment]
> I leave the panel number at 0 but the update created alarm_control_panel.visonic_alarm_2

Have you renamed it within Home Assistant?
If not then please create a debug log file (as per the how to on the wiki), zip up the log file and upload it in this thread

**Comment by open1999** [comment]
No.
First install last year : v8.4.1

Before update  v8.5.2

Panel 0 and "alarm_control_panel.visonic_alarm" was ok.

Yesterday :
- update,
- restart,
- alarm_control_panel.visonic alarm panel was unvalaible

I rebooted the PC still invalid

I discovered the "alarm_control_panel.visonic_alarm_2" that had been created was in the correct state, but I had to configure it again to get everything OK (my post n°2).

[home-assistant_2024-07-27T13-21-30.781Z.log.zip](https://github.com/user-attachments/files/16404502/home-assistant_2024-07-27T13-21-30.781Z.log.zip)

No error in the log.

**Comment by davesmeghead** [comment]
I have no idea why, sorry
Everything in the log indicates that it's panel 0
e.g. `[custom_components.visonic.client] P0`

The Px at the end tells me that client is looking after panel 0.

I assume that you only have 1 panel.

In Developer Tools look at these attributes, what are they set at
![image](https://github.com/user-attachments/assets/7a85965c-5e65-4335-9f58-6189f3fff12f)

**Comment by open1999** [comment]
Yes I have 1 panel Power Max Pro Part

I have also MKP-150/151 is a two-way wireless keypad.

I reinstalled a HA backup.
Same problem if I do visonic's update.

If I delete alarm setup (hub) and add a new hub (alarm) it's ok (logic).

**Comment by HuggiesHA** [comment]
Updated to 0.9.6.7 today and still not connecting on my Power Master

2024-07-28 21:55:28.509 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration visonic which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant


2024-07-29 15:19:10.804 DEBUG (MainThread) [custom_components.visonic] [Visonic Setup] ************************************ create connection ************************************
2024-07-29 15:19:10.805 DEBUG (MainThread) [custom_components.visonic] [Visonic Setup]       Entry id=41f800089d39545ec9091e20ab88d1 in a total of 1 previously configured panels
2024-07-29 15:19:10.805 DEBUG (MainThread) [custom_components.visonic] [Visonic Setup] CONF_PANEL_NUMBER not in configuration, stopping configuration with an error

**Comment by davesmeghead** [comment]
Hi, I'll add it to my bug list to fix it but as you've already installed and run it then I'm sorry but you'll need to delete the integration from home assistant and set it up again, just in settings and 3 dots and Delete, and then setup again. Let me know if that doesn't work.

**Comment by HuggiesHA** [comment]
Fine after re-install. I was just sharing in case the update was meant to resolve the issue.

**Comment by Sudo-Rob** [comment]
I'm having problems with commands.  It could be related to line 18 in this file:

[Visonic_log.txt](https://github.com/user-attachments/files/16431144/Visonic_log.txt)

**Comment by davesmeghead** [comment]
> I'm having problems with commands
OK so I've spotted and fixed a bug, I've got a few other tweaks and I'll create a new release very soon.
It downloaded the EPROM but then got the number of usercodes wrong for your panel type (PM10).
As a temporary fix you could set your usercode in the alarm panel entity settings as Home Assistant have added the default code to be used.

**Comment by Sudo-Rob** [comment]
Updated to 0.9.6.10, but using Core 2024.8.0b1 to debug a weather integration.  

Responsiveness of arm/disarm commands are lethargic to the point of panic when attempting to disarm and nothing happens.

**Comment by davesmeghead** [comment]
Is it OK with Core 2024.7 on your system?

**Comment by Sudo-Rob** [comment]
Same behavior with 0.9.6.10 and Core 2024.7.4.

**Comment by fuglyface** [comment]
Hi
Thanks for the great work on this project
I have same issue on 9.6.5 ~13 . it creates a 2nd panel, first panel shows unavailable 
![visonic PM30](https://github.com/user-attachments/assets/da626be2-da75-4326-a27f-eb89346a43c5)

**Comment by Sudo-Rob** [comment]
I'm also seeing periodic drops into Standard Plus mode.

![image](https://github.com/user-attachments/assets/f3ed0b45-fa49-4e17-8129-58e55535a6c5)

**Comment by davesmeghead** [comment]
> Do you need a log?

Yes please, don't I always!
I've just released 0.9.6.14 but I don't think it'll help you so I'll need a log file.  
It might be easiest if you delete the integration from the settings page and reinstall

**Comment by Sudo-Rob** [comment]
Here ya go:

[Visonic_log_240804.txt](https://github.com/user-attachments/files/16489024/Visonic_log_240804.txt)

I don't see 0.9.6.14 yet, so this is on ~.13

**Comment by Sudo-Rob** [comment]
Seems to be working now.  I'll watch it for a day or two.

Thanks.

**Comment by davesmeghead** [comment]
Closing this issue, if the problem continues then either reopen or create a new issue please
