### ISSUE TITLE
No user code is not working after upgrade to > 0.9

### ISSUE THREAD

**Issue by BornTKill** [davesmeghead/visonic#127]
Dear,

The last major update have broken the arm/disarm with no user code. It was working in 0.8.5

Regards.

**Comment by BornTKill** [comment]
Have to be in powerlink mode 😂

**Comment by davesmeghead** [comment]
And tick the arm without user code in the config. If that doesn't work and you're not in Powerlink and you think you should be then upload a zipped debug log file.
Alternatively enter your user code in the HA alarm panel entity
