### ISSUE TITLE
Update to 0.9.6.14, Stay in Standard Plus Mode and No X10

### ISSUE THREAD

**Issue by ldupont226** [davesmeghead/visonic#132]
Update to 0.9.6.14, Stay in Standard Plus Mode, No X10

Hi Dave thanks for your work. 
Before with 0.8.5.2 version,everything was working perfectly
First if I upgrade to new release (try all including  0.9.6.14)  it create a new Panel
Then I have deleted the previous panel an create a new one

Unable to go to in Powerlink Mode, it stay stay in Standard Plus Mode
The integration get all sensor,But it does'nt get my X10 switchs (Home code K).

I'm running on virtual machine on Poxmox.
I use a raspbeery with Ser2Net to connecte to my Pannel 

Sorry for my poor english 

[home-assistant.log](https://github.com/user-attachments/files/16504717/home-assistant.log)

Rel 0.9.6.14 config
[config_entry-visonic-01J4JM5VH2R5HGR09YBFK0XDJ9.json](https://github.com/user-attachments/files/16504719/config_entry-visonic-01J4JM5VH2R5HGR09YBFK0XDJ9.json)

Rel 0.8.5.2 config
[config_entry-visonic-Previous release.json](https://github.com/user-attachments/files/16504895/config_entry-visonic-Previous.release.json)

**Comment by davesmeghead** [comment]
Hi,
Just a few questions for you, and your English is very good, much better than my foreign languages.  I struggle with English :)

Sorry for you needing to delete and recreate the panel, it should automatically update.

When it gets to Standard Plus, as you have a PowerMax+ panel have you tried to manually enrol from your Alarm Panel menu

Looking at your settings you exclude X10 devices 1,2,3,4,7 and 9.  The integration only finds a single X10 device (number 1), but as it's excluded then a switch is not created.  How many X10 devices do you have?

**Comment by ldupont226** [comment]
For X10 the rest of excluded then 9 devices,
may be a hint, I really don't know, Powermax use by default the  following House code Device 1 for a indoor siren, 
In my case my house code in Powermax is K (device K5,K6,K8,K10,K11,K12,K13,K14,K15) and indoor siren L1.
I don't know if you do a scan or read the house code ?

For the Powerlink I have tried many times (min 10) to delete and re-enroll with only 1 Powerlink successful, but after recharge it lost it,  
With the previsous version, I need to do that only one time , I can recharge and reboot without re-enroll

**Comment by davesmeghead** [comment]
Hi,
I think I've fixed the X10 problem with a release I've just uploaded to Github (0.9.6.16).

If you can:
- Set the log file to debug for this Integration (you seem to have this set already but I'm just making sure)
- Install the old version of the integration (you said 0.8.5.2 above), 
- restart HA, 
- make sure it's enrolled to Powerlink, use the panel if you need to to manually enrol. 
- Then restart HA again, 
- Make sure it enrols as Powerlink without you doing using the panel to enrol
- Upload a log file then I'll see if I can find the problem in the updated code

I can compare the sequence and timing of the messages between the integration and the panel.

**Comment by ldupont226** [comment]
It is not necessary for me to reinstall version 0.8.5.2 because I run on Proxmox, Before doing an update I do a Snapshot. and if it does not work properly I do a roll back. And I am currently with version 0.8.5.2.
So for this test I did a shutdown of my VM and restarted it.
I did not do anything on the console because it was already enrolled.
Thank you

here my log file
[home-assistant.log](https://github.com/user-attachments/files/16516277/home-assistant.log)

**Comment by ldupont226** [comment]
With release 0.9.6.16
Wonderful X10 is working correctly 

Now for the Powerlink 
Time, operation and result:
20:11 Boot.........Alarm connected in Standard Plus and stay
20:18 On Visonic Panel GO installer mode and exit to reset.........Samething stay in Standard Plus
20:26 On Visonic Panel delete Powerlink and reinstall..............Connected in Powerlink Mode
20:32 Rechage VIsonic Integration ...............................Return in  Standard Plus and stay
Log of first Boot
[home-assistant.log](https://github.com/user-attachments/files/16517159/home-assistant.log)
------------------------------------------------------------------
20:46 Restart VM .........Alarm connected in Standard Plus and stay
20:54 On Visonic Panel GO installer mode and exit to reset.........Samething stay in Standard Plus
20:58 On Visonic Panel delete Powerlink and reinstall..............Connected in Powerlink Mode
Log of  second Boot
[home-assistant2.log](https://github.com/user-attachments/files/16517166/home-assistant2.log)

**Comment by davesmeghead** [comment]
I woke up really early this morning to find you'd uploaded log files, thankyou
I think I've spotted the problem and I've released 0.9.6.17 so please give it a try and let me know

**Comment by davesmeghead** [comment]
Oh forgot to ask, can you check the locations for the X10 devices are correct

**Comment by ldupont226** [comment]
Hi Dave
Everythins is perfect, and the X10 locations are the same as in the panel.
Powerlink mode in few seconds.
Thank you so much

**Comment by davesmeghead** [comment]
Thanks for your help, for testing the X10 functionality so comprehensively and for providing all the log files. I'm going to close this issue but if there are further problems then create a new issue
Thanks
Dave
