### ISSUE TITLE
Adjustment of PM Pro Sensors

### ISSUE THREAD

**Issue by eijlers** [davesmeghead/visonic#136]
Hi Dave,

Thank you for your wonderfull HACS integration!

I have 3 sensors which are not recognized correctly. Can you change the following PM Pro Sensors in pyvisonic.py:

ZoneSensorType (row 1066):
 0x75 : ZoneSensorType("Next+ K9-85 MCW", AlSensorType.MOTION ),        # Jan
 0x86 : ZoneSensorType("MCT-426", AlSensorType.SMOKE ),         # Jan
 0x87 : ZoneSensorType("MCT-302", AlSensorType.MAGNET ),        # Jan

The following sensors are ok:
 0x96 : ZoneSensorType("MCT-302", AlSensorType.MAGNET ),
 0xF3 : ZoneSensorType("MCW-K980", AlSensorType.MOTION ),        
 0xFA : ZoneSensorType("MCT-427", AlSensorType.SMOKE ),         

Thx,
Jan.

**Comment by davesmeghead** [comment]
Hi,

I've added this one
0x87 : ZoneSensorType("MCT-302", AlSensorType.MAGNET ), # Jan

But for these 2:
0x75 : ZoneSensorType("Next+ K9-85 MCW", AlSensorType.MOTION ), # Jan
0x86 : ZoneSensorType("MCT-426", AlSensorType.SMOKE ), # Jan

Many people have given me different settings for these sensors in the past, I guess that there was an error in their naming at a point in the production that was fixed so it gives different settings. 
Anyway, when a sensor ends in a "5" or "6" like 0x75, 0x86 the generic type is a Magnet and so I'm keeping it set to the value I already have. You can override the device type in Home Assistant. 

Thanks for passing the info to me though, much appreciated
