### ISSUE TITLE
Button change to Arm Away when Arm Home / Disable in v0.9.6.20

### ISSUE THREAD

**Issue by CaptPilaf** [davesmeghead/visonic#137]
Hi Dave, thanks for all the hard work and all the updates so far. I am using your integration for years on my Powermaster 30 and I am very happy with it. No issues so far but after updating to v.0.9.6.20 my panel behavior in Hassio is strange.

Every time when I press Arm Home or Disable in Hassio, the button changes for a couple of seconds to Arm Away. The panel it self follows the requested command so not changing to Arm Away.
When the panel is Disabled, from time to time the Arm Away pops up and the Disabled button change to Arm Away for a couple of seconds. Again not sending the command to the panel it self.

I have downloaded the homeassistant.log as described in your wiki but no clue where to look.

https://www.dropbox.com/scl/fi/3vq9iyo7p8z0qr3dutyiq/home-assistant.log?rlkey=s898den4wejbkp1fiesylttue&dl=0

Regards,

Ollie

![IMG_0972](https://github.com/user-attachments/assets/e8d1307b-de4a-4797-be58-975f96719972)

**Comment by davesmeghead** [comment]
Hi

Are you able to download a zipfile from Github and install the code manually?
https://github.com/davesmeghead/visonic/tree/dev_b0

Click Green 'Code' and the Download Zip

I've just uploaded dev_B0 Release on Github, please give it a try

In the background I've been rewriting the low level interaction with the panel to centralise it and make it easier for me to understand and debug.

Thanks for your help
Dave

**Comment by CaptPilaf** [comment]
Hi Dave,Thanks,I have installed your version manually and it now says v0.9.7.2I’ll test the alarm tonight and upload the new debug file you for troubleshooting, but for now it looks ok to me.Regards,OllieVerstuurd vanaf mijn iPadOp 17 aug 2024 om 18:35 heeft davesmeghead ***@***.***> het volgende geschreven:﻿
Hi
Are you able to download a zipfile from Github and install the code manually?
https://github.com/davesmeghead/visonic/tree/dev_b0
Click Green 'Code' and the Download Zip
I've just uploaded dev_B0 Release on Github, please give it a try
In the background I've been rewriting the low level interaction with the panel to centralise it and make it easier for me to understand and debug.
Thanks for your help
Dave

**Comment by CaptPilaf** [comment]
Hi Dave,All is working fine now, system is stable again.Once more, thanks for the hard work and making this integration possible.Regards,OllieFYI, my stable hassio log file is in my dropboxhome-assistant 4.logdropbox.com

**Comment by davesmeghead** [comment]
Closing this issue, if the problem continues then either reopen or create a new issue please
