### ISSUE TITLE
After 0.9.6.20 install commands don't get triggered after minutes of reloading integration

### ISSUE THREAD

**Issue by vdiogo** [davesmeghead/visonic#138]
I have updated this integration to 0.9.6.20 as I was experiencing regular disconnection problems (had to reload integration and/ or enter into installer mode in the alarm and exit again)

I noted this new version brought a new alarm console to trigger commands, the commands labels were updated (eg from arm_away to Arm Away) and some services were updated (eg reload) so I adjusted all of my automations (node-red) accordingly.

Now, the commands are not being triggered (from the UI or calling the service visonic.alarm_panel_command). I reload the integration, the commands work, and some minutes after stop working again.

This is the log when the command doesn't work:
`2024-08-11 18:50:23.994 DEBUG (MainThread) [custom_components.visonic.binary_sensor] [binary sensor _retainStateTimout out]   unique_id = visonic_z03   timeout = 120    current = False`

**Comment by davesmeghead** [comment]
Hi,
That log entry doesn't really help me, I'd need a debug log file, zipped and loaded here please.
Are you able to grab a dev release from Github and are willing to try it, not the current dev but soon.
Regards
Dave

**Comment by vdiogo** [comment]
Thanks for the reply. Debug log attached

As for trying a dev release, I can give it a try if you can help me on how to install it
[home-assistant_visonic_2024-08-15T17-52-41.137Z.log.zip](https://github.com/user-attachments/files/16628382/home-assistant_visonic_2024-08-15T17-52-41.137Z.log.zip)

**Comment by davesmeghead** [comment]
Hi,
I've had a look at your log file and I think the dev_B0 release will help you.

You can download it here
https://github.com/davesmeghead/visonic/tree/dev_b0

Select the green code and then download zip.

You then need to go to your Home Assistant config directory (where the log file is located) and go into custom_components, replace the visonic directory with the visonic directory in the zip file.

Restart Home Assistant

Dave

**Comment by vdiogo** [comment]
Thanks. Just did as suggested. Commands seems to be working (since 5min at least) so will keep an eye and report here.
One new thing that came was the following notification that I didn't saw before:
<img width="430" alt="image" src="https://github.com/user-attachments/assets/acb1b349-18cd-45a8-b50e-4e5e0384617d">

**Comment by davesmeghead** [comment]
Hi

That notification means that the Integration doesn't have a user code for your panel, I'd need a log file to work out why. But please try the new code first .....

In the background I've been rewriting the low level interaction with the panel to centralise it and make it easier for me to understand and debug. 
I've just uploaded dev_B0 Release on Github, please give it a try

Thanks for your help
Dave

**Comment by davesmeghead** [comment]
I've just uploaded a new dev_B0 Release on Github, please give it a try
Dave

**Comment by vdiogo** [comment]
Apologies, been on leave. Back and downloaded new version... testing

**Comment by vdiogo** [comment]
Whilst panel can be armed/ disarmed, Sensors show unavailable:
<img width="430" alt="image" src="https://github.com/user-attachments/assets/77071217-3c28-44fb-8b20-1cb06c9fe3c9">

**Comment by davesmeghead** [comment]
Hi,
I've just released "0.9.7.9 - English Translation File, Logic Updates and Bug Fixes" to dev_B0, if you get the chance please give it a try. If your problem persists with this release then I'll need a debug HA log file
Dave

**Comment by vdiogo** [comment]
Thanks for the release. Downloaded and testing now

**Comment by vdiogo** [comment]
Same problem as before (sensor shows unavailable). Log attached
[home-assistant_visonic_2024-09-02T07-36-22.054Z.log](https://github.com/user-attachments/files/16833769/home-assistant_visonic_2024-09-02T07-36-22.054Z.log)

**Comment by davesmeghead** [comment]
Can you please update Home Assistant to the latest version please, at least 2024.8.1.
I have added model_id as an attribute and it's failing on that, this was introduced in the 2024.8.1 release.

**Comment by davesmeghead** [comment]
There are a lot more errors from other integrations as well in that log file

This is the 'model_id' error in the file
```
2024-09-02 08:29:10.656 DEBUG (MainThread) [custom_components.visonic.client] P0  Adding Sensor id=1  Type=Motion   Loc=not_installed  ztypeName=delay_1    ztamper=0  ztrip=0  zchime=chime_off        bypass=0  lowbatt=0  status=0  tamper=0  enrolled=1  triggered=0 
2024-09-02 08:29:10.669 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entity None for domain binary_sensor with platform visonic
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 770, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'model_id'
```

**Comment by vdiogo** [comment]
Let me check the release notes on 2024.8 and will do at the first chance (I like to be outdated 1-2 major releases and update to latest first on another less critical HA environment as had some problems before)

**Comment by vdiogo** [comment]
Updated to 2024.8 and issue has been fixed:
<img width="430" alt="image" src="https://github.com/user-attachments/assets/58da7f46-ea98-48fe-bfe4-3acb6c0ea0d4">

**Comment by davesmeghead** [comment]
Hi,
I've just released dev_B0 0.9.8.0 as per the main forum, can you make sure that this dev release doesn't break it again :wink:
https://community.home-assistant.io/t/visonic-powermax-and-powermaster-integration/316702/538

Dave

**Comment by vdiogo** [comment]
Hey Dave! Was away. Just installed it, will keep an eye on it

**Comment by vdiogo** [comment]
Hi! So far the only issue is that when you call the armed_home action, it triggers the armed_away service.

**Comment by vdiogo** [comment]
Here goes my log
[home-assistant_visonic_2024-09-27T16-08-10.082Z.log](https://github.com/user-attachments/files/17166873/home-assistant_visonic_2024-09-27T16-08-10.082Z.log)

**Comment by davesmeghead** [comment]
I'm not sure what's going on with your setup. What I can confirm by looking at your log file though is that the command that is being passed to this integration is the same as the command sent to the alarm panel. 
I'm not really sure what to suggest next. 
Which action are you using (although I have tested both).  Are you using the built in 
![image](https://github.com/user-attachments/assets/ce4706e0-5c62-47fb-b414-04600fbc7d7c)

or the service that I create
![image](https://github.com/user-attachments/assets/7ca3a98d-4612-429b-b1aa-6f16a6c5e941) 

Can you try both of these please (exactly as above).

The only real change recently is the addition of language and I noticed in your log file that you have it set to Portuguese.  Could you experiment and change the language to English (I'm assuming that you can do this as you're typing English in this issue :smile:. 
Click on your icon in Home Assistant (usually bottom left) and change the language
![image](https://github.com/user-attachments/assets/d023211e-d1c2-4105-ac6c-e2c485c1e675)

Then try it again please

**Comment by vdiogo** [comment]
Nevermind me: this alarm is connected to another one in NodeRed (purpose is to have them in synch) and this ended on a loophole which set the Visonic to be Armed Away when originally was set a Armed Home 🤕

Fixed it and its working like a charm

**Comment by davesmeghead** [comment]
That's OK. I'll close this issue.
