### ISSUE TITLE
connection problems after update 0.9.6.21

### ISSUE THREAD

**Issue by Github2018lb** [davesmeghead/visonic#140]

**Comment by davesmeghead** [comment]
I'm not sure how you expect me to do anything about it without a description, or even better a debug HA log file.
If you don't reply with a log file I'll close this issue.
Regards
Dave

**Comment by Github2018lb** [comment]
Hi davesmeghead,First of all, sorry. You can close this issue, i solved the issue by restoring a backup. The problem reoccurs when a new version becomes available and i did not configure the reconnect attempts Kind regards,Please consider your environmental responsibility before printing this e-mailSent from my iPhoneOn 14 Aug 2024, at 18:02, davesmeghead ***@***.***> wrote:﻿
I'm not sure how you expect me to do anything about it without a description, or even better a debug HA log file.
If you don't reply with a log file I'll close this issue.
Regards
Dave
