### ISSUE TITLE
0.9.6.21 - sometimes impossible to arm or disarm alarm

### ISSUE THREAD

**Issue by g4seb** [davesmeghead/visonic#146]
Hi @davesmeghead, as i say on home assistant forum, sometimes it's impossible to arm or disarm alarm.
Obligation to reboot HA and after it's ok.
I try 2, 3 times to arm …nothing append. After that i put arm with a official remote.
Same case to disarm :-)

This is my log files : https://www.dropbox.com/scl/fi/6il5wdjarm9dl7vlnl4uw/home-assistant.log?rlkey=6ohxihhxjb0gp91pfj9bvkysd&st=3o6ocsub&dl=0

**Comment by davesmeghead** [comment]
Hi
OK thanks for the log file, I've made quite a few changes because of this.  Do you know when you look at something to fix and the changes just keep going on and on and on :wink:

Please try dev_B0 0.9.7.7 release

**Comment by g4seb** [comment]
> OK thanks for the log file, I've made quite a few changes because of this. Do you know when you look at something to fix and the changes just keep going on and on and on

😉 Yes i know; it's difficult for you ...Ok i try this thanks

**Comment by open1999** [comment]
I'v tested this version.

Warning "Lookup of Visonic Zone Type Reference Invalid, 2 is not in the array" line 160
[home-assistant_2024-08-26T22-03-37.138Z.log.zip](https://github.com/user-attachments/files/16754312/home-assistant_2024-08-26T22-03-37.138Z.log.zip)

**Comment by davesmeghead** [comment]
Thankyou for that but I realised that the log won't tell me what I need to know, can you do it again please.  I've just posted on the main forum here:
https://community.home-assistant.io/t/visonic-powermax-and-powermaster-integration/316702/523

**Comment by davesmeghead** [comment]
I've just released "0.9.7.9 - English Translation File, Logic Updates and Bug Fixes" to dev_B0, if you get the chance please give it a try.

**Comment by davesmeghead** [comment]
Hi,
I've just released dev_B0 0.9.8.0 as per the main forum
https://community.home-assistant.io/t/visonic-powermax-and-powermaster-integration/316702/538

Please give it a try
Dave

**Comment by davesmeghead** [comment]
I'll close this issue as I've just created a HACS Master release 0.9.9.3. 
Any further problems (with 0.9.9.3) I'd rather they were in new issues please.
