### ISSUE TITLE
Attributes lastevent, lasteventname and  System lasteventaction stopped updating

### ISSUE THREAD

**Issue by Joao-Sousa-71** [davesmeghead/visonic#149]
Dave, 
It only happen once but with the beta version 0.9.7.7 the alarm attributes stop updating with the alarm state.
See the following, the alarm is disarmed

```
code_format: null
changed_by: System
code_arm_required: false
mode: Powerlink
state: Disarmed
ready: true
tamper: false
memory: false
siren: false
bypass: false
alarm: None
trouble: None
lastevent: System/Quick Arm Away
lasteventname: System
lasteventaction: Quick Arm Away
lasteventtime: 28/08/2024, 19:58:00
Protocol Version: 1.4.1.0
Panel Model: PowerMax Pro Part
Power Master: "No"
Watchdog Timeout (Total): 0
Watchdog Timeout (Past 24 Hours): 0
Download Timeout: 0
Download Message Retries: 0
Panel Problem Count: 0
Last Panel Problem Time: ""
Client Version: 0.9.7.7
Exception Count: 0
panel: 0
friendly_name: Visonic Alarm
supported_features: 3
```
But the previous Quick Arm Away didn't change, and then I've Armed Home and also didn't update.

**Comment by Joao-Sousa-71** [comment]
An update to this issue. Restarting HA several times didn't fix it, however enter on the panel enter on the installer menu and leaving the events started to update again. If happens again I will enable the log and share it here.

**Comment by davesmeghead** [comment]
I've just releases "0.9.7.9 - English Translation File, Logic Updates and Bug Fixes" to dev_B0, if you get the chance please give it a try.

**Comment by Joao-Sousa-71** [comment]
I've just install the 0.9.7.9. Keep you posted.

**Comment by Joao-Sousa-71** [comment]
@davesmeghead 

Have the 0.9.7.9 installed and still have at least one issue. See the state of the alarm (disarmed) which is not consistent with the lasteventname/ lasteventaction / lasteventime data since the alarm waas disarmed today in the morning:

```
code_format: null
changed_by: System
code_arm_required: false
mode: powerlink
state: disarmed
ready: true
tamper: false
memory: false
bypass: false
alarm: none
trouble: general
Protocol Version: 1.4.1.2
Panel Model: PowerMax Pro Part
Power Master: "No"
Watchdog Timeout (Total): 0
Watchdog Timeout (Past 24 Hours): 0
Download Timeout: 0
Download Message Retries: 0
Panel Problem Count: 0
Last Panel Problem Time: ""
lastevent: System/Quick Armed Away
lasteventname: System
lasteventaction: Quick Armed Away
lasteventtime: 06/09/2024, 09:12:12
Client Version: 0.9.7.9
Exception Count: 0
panel: 0
friendly_name: Visonic Alarm
supported_features: 3
```
 in the meantime I've enabled the debug log attached but with teh Home Assistant restart the fields were updated :-(

```
friendly_name: Visonic Alarm
supported_features: 3
code_format: null
changed_by: Startup
code_arm_required: false
mode: powerlink
state: disarmed
ready: true
tamper: false
memory: false
bypass: false
alarm: none
trouble: general
Protocol Version: 1.4.1.2
Panel Model: PowerMax Pro Part
Power Master: "No"
Watchdog Timeout (Total): 0
Watchdog Timeout (Past 24 Hours): 0
Download Timeout: 0
Download Message Retries: 0
Panel Problem Count: 0
Last Panel Problem Time: ""
lastevent: Startup/Startup
lasteventname: Startup
lasteventaction: Startup
lasteventtime: 10/09/2024, 15:04:36
Client Version: 0.9.7.9
Exception Count: 0
panel: 0
```
But maybe you can find something in the log.

[home-assistant_Debug Log 0.9.7.9 for Dave 10092024.zip](https://github.com/user-attachments/files/16946318/home-assistant_Debug.Log.0.9.7.9.for.Dave.10092024.zip)

Please let me know if makek sense to try with 0.9.7.10 or wait for a later beta version.
Thank you, João

**Comment by davesmeghead** [comment]
Hi,
I've introduced a coordinator to try and manage the various states and events and so they should now be consistent, just released dev_B0 0.9.8.0 as per the main forum
https://community.home-assistant.io/t/visonic-powermax-and-powermaster-integration/316702/538

Thanks for the comment, please give the release a try
Dave

**Comment by Joao-Sousa-71** [comment]
@davesmeghead 

Version installed.

```
friendly_name: Visonic Alarm
supported_features: 3
code_format: null
changed_by: System
code_arm_required: false
panel: 0
mode: powerlink
state: disarmed
ready: true
tamper: false
memory: false
bypass: false
alarm: none
trouble: none
Protocol Version: 1.4.2.0
Panel Model: PowerMax Pro Part
Power Master: "No"
Watchdog Timeout (Total): 0
Watchdog Timeout (Past 24 Hours): 0
Download Timeout: 0
Download Message Retries: 0
Panel Problem Count: 0
Last Panel Problem Time: ""
lastevent: System/Disarmed
lasteventname: System
lasteventaction: Disarmed
lasteventtime: 17/09/2024, 13:00:59
Client Version: 0.9.8.0
Exception Count: 0
```
Keep you posted.
Thank you.

**Comment by davesmeghead** [comment]
I'll close this issue as I've just created a HACS Master release 0.9.9.3. 
Any further problems (with 0.9.9.3) please create a new issue.

**Comment by Joao-Sousa-71** [comment]
Agree. So far didn't happen again.
