### ISSUE TITLE
Partitions

### ISSUE THREAD

**Issue by adznon** [davesmeghead/visonic#150]
Hello Dave,

Is adding partitions something that will be added in the future.

Its the only thing stopping me being able to fully use your integration at the moment for my use case.

Thanks
Adznon

**Comment by davesmeghead** [comment]
Hi,
I've added it as an enhancement, it's on my "todo" list but it won't be soon, probably before then end of the year but no promises
Regards
D

**Comment by adznon** [comment]
Thanks Dave, very much appreciated
