### ISSUE TITLE
0.9.8.0 - Instant Arm Home not working (arming with the usual delay)

### ISSUE THREAD

**Issue by EyalRotem** [davesmeghead/visonic#155]
Hi, 
I haven't tried using this before the latest test version. but now i have tried and it just arms regularly - status updates to "arming" and then it is armed.

here's a log (I've tried 2 times):
[log.log](https://github.com/user-attachments/files/17070704/log.log)

**Comment by davesmeghead** [comment]
Hi,

When the panel is "Arming" it does not show that it is "Instant", just that it's arming.

Looking at the log file you actually try 3 times but in all cases you do not wait until the panel is armed.

At 09:06:29 you Arm Home Instant using a service/action in HA
     this shows as Arming Home  (as there is no panel output equivalent to Arming home Instant)
     as far as I can tell it sends the "Instant" command to the panel
At 09:06:45 (only 16 seconds later) you then command Arm Home using a service/action in HA
     the panel starts Arming Home again
At 09:06:50 (only 5 seconds later) you then command Arm Home Instant using a service/action in HA
     the panel starts Arming Home again
At 09:06:57 (only 7 seconds later) you then use HA to Disarm (not using a service/action)

So in the space of 34 seconds you try to arm the panel 3 times and then disarm it.  You do not let the arming time complete to get to the armed state.

Let me try and summarise the functionality:
- Arming does not differentiate normal or instant
- When the panel is armed (i.e. the arming has been allowed to finish which your log file never gets to) the integration shows Armed for both normal and instant.  This is so I can merge the information to support the common output of panel state. This is work in progress and I should be able to put back "Armed Home Instant" and "Armed Away Instant" in the "state" attribute.

Dave

**Comment by davesmeghead** [comment]
this has got me wondering if there is an arming instant or not, let me look at it, I'll add it to my todo list
Dave

**Comment by EyalRotem** [comment]
Yes, indeed I did not  wait. As I thought that instant means it doesn’t wait for the panel delay to arm. Maybe I haven’t understood the functionality.
But the behavior of “arm home” and 
“Arm home instant” behave the same as I see it.
I don’t really need the status to be correct in that manner.

I will try to explain my usage though- I have curtain sensors which gets triggered if the shutters are moving. As of today I use a 60 seconds arm delay because of that (shutters close while “arming”).
What I thought of doing is when all shutters are down - arm instantly to avoid waiting if it is not needed.


Thanks for replying !

**Comment by davesmeghead** [comment]
> Yes, indeed I did not wait. As I thought that instant means it doesn’t wait for the panel delay to arm. Maybe I haven’t understood the functionality.

'Instant' is all about disarming the alarm.  It does not do the **entry delay**.

It is described in the visonic manuals like this

Instant: You can arm the system AWAY-INSTANT or HOME-INSTANT, thereby canceling the entry delay for all delay zones for the duration of one arming period.

**Comment by EyalRotem** [comment]
Well that’s definitely my bad then. I didn’t understand it correctly.. 
any way of arming immediately than?😅
