### ISSUE TITLE
Connect to RS232 port Alarm

### ISSUE THREAD

**Issue by ShaneGooseman** [davesmeghead/visonic#16]
How do you connect the ethernet module to the alarm?
Do you have the connection cable scheme?

**Comment by davesmeghead** [comment]
Hi,
Have a look at the [Wiki](https://github.com/davesmeghead/visonic/wiki#example-hardwaresoftware-setup)
Click the link [there](https://github.com/davesmeghead/visonic/wiki/Using-NodeMCU-PowermaxProModel6#using-nodemcu) and this gives you an example of a device that could be used and the wiring schema to the panel.

Hope this helps
If you have any problemt then there's an active forum about the component [here](https://community.home-assistant.io/t/visonic-powermax-and-powermaster-component/55949)
D
