### ISSUE TITLE
Disabled Entity - Got an unexpected keyword argument 'model_id'

### ISSUE THREAD

**Issue by thefrip** [davesmeghead/visonic#162]
Hello,
Just upgraded to 0.9.9.3 coming from 0.9.6.21 (I was getting the issue on the arm/disarm becoming irresponsive after some time) and "lost" all my sensors (ie. reported as no longer provided by the integration).

Log reports:

Error adding entity None for domain binary_sensor with platform visonic

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 770, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'model_id'

**Comment by davesmeghead** [comment]
Please update your Home Assistant to the latest version.
