### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by swemaverick** [davesmeghead/visonic#164]
Hi, just new to this plugin and about to install it in HA, via HACS. But when clicking to add the integration, I end up in this screen; 
![image](https://github.com/user-attachments/assets/edee82d0-b780-4e7f-9003-a199b78621a2)
. So waht is the issue here? (running latest HA, 2024.10.02

**Comment by davesmeghead** [comment]
Hi, did you restart Home Assistant after installing it from HACS?

**Comment by swemaverick** [comment]
Yes it was restarted, but for some reason it had issues downloading. now it's downloaded and I can see it in integrations. But when I try to add my Powermaster 10 and entering the IP it has on my network it does not activate or gets discovered. How do I add it to my HA system? I have the correct ip filled in. Any setting in the PM10 I need to activate to allow this kind of integration?

**Comment by davesmeghead** [comment]
What hardware are you using in your panel?
See this issue, you are not able to use the Powerlink 3 hardware at this time
https://github.com/davesmeghead/visonic/issues/165

If you are using an ESP device for example and think you've connected it up correctly then zip up a debug log file and upload if in this thread

**Comment by swemaverick** [comment]
yes, using powerlink 3.1, so then that's the issue then. Any plans of getting powerlink 3 into this integration or is it now possible?

**Comment by davesmeghead** [comment]
possible: not at the moment
plans: yes, but no timescales

**Comment by davesmeghead** [comment]
Hi, this has been released as a supported capability, see this post first and go from there
https://community.home-assistant.io/t/visonic-powermax-and-powermaster-integration/316702/572

**Comment by davesmeghead** [comment]
I'll close this issue, feel free to reopen or create a new issue
