### ISSUE TITLE
Powermaster 33 : Visonic panel does not appear to be fully connected or initialized as it is in the 'starting' state and its status is unknown.

### ISSUE THREAD

**Issue by githubpreny** [davesmeghead/visonic#165]
Hello Daves,

I am trying to install Visonic Alarm Panel for Home Assistant that you have developed.
I have a Powermaster 33 equipped with powerlink 3.

I can see on my internal network that the IP address of my Visonic Alarm is _192.168.1.20_.
I have also noticed on _192.168.1.20_ that ports _21_ and _8181_ are open.

After restarting HA, I am setting up the Integration and I have a few questions:

In the **Connection Settings**
- I am indeed selecting "Ethernet", as my alarm is connected to my internal network through LAN, so my HA server;
- In French language, it is written "please enter the Central number". By default, it is "0". In English, does it mean "Panel number" ? I am not sure that I have understood correctly what it is related to.

Next screen is: 
**Ethernet Configuration**
- "Host IP address" : by default, it shows 127.0.0.1; should I replace by 192.168.1.20 as it is the IP address of my Visonic Alarm on my local network ?
- "Port" : by default it is showing 30000. Should I use 21, or 8181, or leave it with 30000 ? Anything else ?

Many thanks.
FROG

**Comment by davesmeghead** [comment]
Hi,
I'm sorry but at this moment in time you are not able to use this integration with a Powerlink 3 hardware module. You would need to replace the Powerlink hardware module with a "gadget" such as [here](https://github.com/davesmeghead/visonic/wiki/Hardware-Setup#hardware-setup) on the wiki
Have you seen the [wiki](https://github.com/davesmeghead/visonic/wiki)?
Dave

**Comment by githubpreny** [comment]
I understand, this is not yet a suitable interfacing with what you have developped.
Yes, indeed, I read several times the Wiki section, as I thought that I did something wrong.

**Comment by davesmeghead** [comment]
Hi,
I/we have just released this as a supported capability, please read this post
https://community.home-assistant.io/t/visonic-powermax-and-powermaster-integration/316702/572

**Comment by davesmeghead** [comment]
I'll close this issue, feel free to reopen or create a new issue
