### ISSUE TITLE
New error appeared following latest update when commuting the state of the alarm

### ISSUE THREAD

**Issue by iaxexo** [davesmeghead/visonic#168]
Since the latest update I often get some disconnections so that i can force the state of the alarm but i cant read it properly.
I had no time to investigate yet but i'll try to get as much info as possible and post a follow up

```
This error originated from a custom integration.

Logger: custom_components.visonic.pyvisonic
Source: custom_components/visonic/pyvisonic.py:2415
integration: Visonic Intruder Alarm (documentation, issues)
First occurred: 09:09:42 (1 occurrences)
Last logged: 09:09:42

'str' object cannot be interpreted as an integer
```

**Comment by iaxexo** [comment]
[home-assistant_visonic_2024-10-29T12-34-15.585Z.log](https://github.com/user-attachments/files/17556827/home-assistant_visonic_2024-10-29T12-34-15.585Z.log)
Attaching debug log

**Comment by davesmeghead** [comment]
Hi,
I thought that I'd already seen and squashed that bug, you've cut lines from the log file and I can't determine what's going on, but first of all, what version of the integration are you using (that's the first thing I look for in the log file and you've removed it). It might have been the dev release that I fixed it in but I thought it was the master / HACS release.

**Comment by EyalRotem** [comment]
this happened to me as well. after "arming home" or "disarming" for example - the entity becomes unavailable. sometimes it will recover, and sometimes not.
reverting to the old version (0.9.9.3) works like a charm.

log: 
[home-assistant_2024-10-29T19-50-50.340Z.log](https://github.com/user-attachments/files/17562351/home-assistant_2024-10-29T19-50-50.340Z.log)

**Comment by davesmeghead** [comment]
I had squashed the bug but in the dev version, I've updated the master release as 0.9.9.8, please give it a try before I make it a HACS release.

**Comment by EyalRotem** [comment]
Exception is now different ''''int' object has no attribute 'data''''
from the frontend it just looks like this - i arm/disarm, entity becomes unavailable. i than used my fob to disarm and the entity reappeared.

[home-assistant_2024-10-30T04-24-06.219Z.log](https://github.com/user-attachments/files/17566011/home-assistant_2024-10-30T04-24-06.219Z.log)

**Comment by iaxexo** [comment]
> Hi, I thought that I'd already seen and squashed that bug, you've cut lines from the log file and I can't determine what's going on, but first of all, what version of the integration are you using (that's the first thing I look for in the log file and you've removed it).

Sorry I'm away from home, I'll be able to help during the weekend :S
I am running 0.9.9.7, I did not mean to cut the log

**Comment by davesmeghead** [comment]
Ah yeah, I created a 2nd bug, I've updated the master release again as 0.9.9.9, please give it a try before I make it a HACS release.

**Comment by EyalRotem** [comment]
I’ve tested it initially and the exceptions are gone, also the panel reacts and updates as expected 💪🏼

I would like to at least test it through the next day and check that it’s robust. But it seems this bug is squashed💪🏼

**Comment by rodakswe** [comment]
I can also confirm the panel seems to behave normal in 0.9.9.9 version. No errors and the state of the panel remains normal.

**Comment by davesmeghead** [comment]
Thanks for doing a test for me.....
I've made 0.9.9.9 in to a HACS release, for the simple reason that the 0.9.9.7 release has a known bug.

**Comment by iaxexo** [comment]
Never seen that issue again, thank you very much Dave, as always very helpful!

**Comment by iaxexo** [comment]
Never seen that issue again, thank you very much Dave, as always very helpful! 
(sorry if im late at closing this of if it is not right for me to close it, i am a newbie here)
