### ISSUE TITLE
Help setting up Powermaster 360R

### ISSUE THREAD

**Issue by BNWEIN** [davesmeghead/visonic#169]
Hi. I’m so sorry to ask here, but any chance someone could guide me on the setup of a Powermaster 360R? The docs confuse me a little (me issue rather than the docs issue) about whether I can have this on HA without plugging into USB? 

I tried the setup, entered the IP of my alarm pad but for what ever reason it doesn’t work. 

Any help appreciated!

thanks

**Comment by davesmeghead** [comment]
Hi,
I got a working system using USB with a direct connection to the hardware running HA.
If you want to keep using Ethernet and the Visonic Go App then see here:
https://community.home-assistant.io/t/visonic-powermax-and-powermaster-integration/316702/572

**Comment by davesmeghead** [comment]
I'll close this issue, feel free to reopen or create a new issue
