### ISSUE TITLE
Visonic 0.9.9.9 - imposible to use siren.visonic_s01

### ISSUE THREAD

**Issue by g4seb** [davesmeghead/visonic#170]
As i says in HA forum, it's impossible for me to use triggered when triggered by a sensor.

[home-assistant_2024-11-11T10-31-56.055Z.log](https://github.com/user-attachments/files/17700945/home-assistant_2024-11-11T10-31-56.055Z.log)

[home-assistant_2024-11-12T08-11-48.459Z 1.log](https://github.com/user-attachments/files/17713299/home-assistant_2024-11-12T08-11-48.459Z.1.log)

**Comment by davesmeghead** [comment]
Both log files look OK to me

Note that you have a PowerMax Panel and so you will not be able to trigger your siren using this integration.
As for the action not working, I responded to this in the Forum.

**Comment by davesmeghead** [comment]
I'll close this issue, feel free to reopen or create a new issue
