### ISSUE TITLE
Can't controll panel

### ISSUE THREAD

**Issue by phoenix-blue** [davesmeghead/visonic#171]
Since the last Home Assistant update, I’m unable to control the alarm panel via Telegram or the Assistant. The HA log file shows the following errors:

Logger: homeassistant.const
Source: helpers/deprecation.py:222
First occurred: 16:45:11 (16 events)
Last logged: 16:45:18

STATE_ALARM_TRIGGERED was used in the visonic integration, which is a deprecated constant and will be removed in HA Core 2025.11. Please use AlarmControlPanelState.TRIGGERED instead and report this to the author of the 'visonic' custom integration.
STATE_ALARM_ARMED_AWAY, STATE_ALARM_ARMED_HOME, STATE_ALARM_DISARMED, and STATE_ALARM_TRIGGERED were used in the eufy_security integration, all of which are deprecated constants scheduled for removal in HA Core 2025.11. Please use AlarmControlPanelState equivalents and report this to the author of the 'eufy_security' custom integration.
Additionally:

Logger: homeassistant.components.alarm_control_panel
Source: components/alarm_control_panel/init.py:210
Integration: Alarm Control Panel ([documentation](https://www.home-assistant.io/integrations/alarm_control_panel), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+alarm_control_panel%22))
First occurred: 16:45:17 (4 events)
Last logged: 16:45:18

Entity None (<class 'custom_components.visonic.alarm_control_panel.VisonicAlarm'>) is setting state directly, which will stop working in HA Core 2025.11. Entities should implement the alarm_state property and return their state using the AlarmControlPanelState enum. Please report this to the custom integration author.
Is there a fix planned for this?

**Comment by davesmeghead** [comment]
Hi,
Thanks for letting me know.
These are not Errors, they are deprecation warnings that these will stop working by the defined date so there is no urgency

Although this part is nothing to do with me, it's from your eufy integration

> STATE_ALARM_ARMED_AWAY, STATE_ALARM_ARMED_HOME, STATE_ALARM_DISARMED, and STATE_ALARM_TRIGGERED were used in the eufy_security integration, all of which are deprecated constants scheduled for removal in HA Core 2025.11. Please use AlarmControlPanelState equivalents and report this to the author of the 'eufy_security' custom integration.
Additionally:

> Is there a fix planned for this?

I'm already aware of these changes and:
- For the master release I have until November 2025 to update the integration
- I've already made the change in the dev release if you want to install that instead of the master

> Since the last Home Assistant update, I’m unable to control the alarm panel via Telegram or the Assistant. 

Having said that, updating may not fix your problem. I'd need a debug log file please to take a proper look

**Comment by phoenix-blue** [comment]
Hi,

see that I pasted the wrong part of the log.

I have the same issue with Eufy.

When I try to operate the alarm system (panel), I get the following message:

Logger: homeassistant.helpers.intent
Source: helpers/intent.py:1067
First occurred: 19:48:04 (1 events)
Last logged: 19:48:04

Service call failed for alarm_control_panel.visonic_alarm_2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/intent.py", line 1067, in async_handle_states
    await service_coro
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 631, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/intent/__init__.py", line 225, in async_call_service
    raise intent.IntentHandleError(
homeassistant.helpers.intent.IntentHandleError: Service turn_off does not support entity alarm_control_panel.visonic_alarm_2

**Comment by davesmeghead** [comment]
The answer seems to be in the last line

> Service turn_off does not support entity alarm_control_panel.visonic_alarm_2

You cannot turn_on and turn_off the Alarm Control Panel Entity, it is not a switch or a light

**Comment by davesmeghead** [comment]
I'll close this issue, feel free to reopen or create a new issue
