### ISSUE TITLE
Works for a while, then PowerMax Pro starts beeping

### ISSUE THREAD

**Issue by macsatcom** [davesmeghead/visonic#22]
Thanks for the integration, has been working for me well in the past.

After some of the later updates of Home Assistant, it is working for some time after HA startup (sometimes a few hours, sometimes a day or so) the visonic starts beeping warning beeps.

A restart of HA solves it....for some time. Then it starts again.

I am connecting using an ESP32 with ESPLINK - this seem to be stable...

Any idea on what is wrong?

**Comment by davesmeghead** [comment]
I don't know sorry, the only way for me to work it out for you is for you to create a log file and upload it to pastebin or dropbox. Either reply here with the link to pastebin or create an entry in the HA forum thread [here](https://community.home-assistant.io/t/visonic-powermax-and-powermaster-component/55949)

**Comment by davesmeghead** [comment]
No response from macsatcom here or in the HA Forum so closing this issue
