### ISSUE TITLE
Not an issue  - just need help

### ISSUE THREAD

**Issue by declan2511** [davesmeghead/visonic#27]
Hi has anyone connected to a 12 pin rs232 port on a Visonic Powermax+ panel.  I have read lots of conflicting connection info on the web and would appreciate any help in regard to a definitive wiring diagram.  I do have a very old powerlink device, working  now for 14 years  -so I know connection is possible.  I am planning to use Wemos D1 with ESP-link for connectivity - so far I have tried:

[.]   [.]   [.]       [.] [.] [.]
[tx] [rx] [gnd] [.] [.] [5v]........RJ45 socket

Thanks,  if I know the connection is correct I can then start working on other issues.

**Comment by davesmeghead** [comment]
Hello,
A 12 pin socket is a new one on me, they are usually 10 pins (2 rows of 5).
You're better off posting on the Home Assistant forum to ask for help as it's probably only me that looks here and I'm afraid I don't know.
I'll close this but create a post in this thread and other people may be able to help you
https://community.home-assistant.io/t/visonic-powermax-and-powermaster-component/55949/1627
