### ISSUE TITLE
sensors as badges

### ISSUE THREAD

**Issue by piniSolomon** [davesmeghead/visonic#29]
hi,
thanks for this awesome work you do.
I'm setting all the Visonic sensors as badges in my hass but I noticed that once the sensor is triggered only the icon changes and not the color. When the entity is on the card and not as a badge the color and the icon change.
Is there a way to make the badge also change color? because the icon change is very subtle.

**Comment by davesmeghead** [comment]
Hi and thankyou,
The Home Assistant software architecture divides the frontend (what you see) from the backend. This integration is a backend capability to interface to the alarm panel and I reuse existing badges, icons, panels etc from the frontend.  In other words, you need to make changes to the frontend which is not something I know much about. I've got it working for myself but customising it is another step.  So, I'm closing this issue as there's nothing I can do or help you with. I suggest that you post in the main forum [link here ](https://community.home-assistant.io/t/visonic-powermax-and-powermaster-component/55949) and other users of this integration may be able to help you, they have helped me in the past with my frontend problems.
