### ISSUE TITLE
missing component?

### ISSUE THREAD

**Issue by Joakimcc** [davesmeghead/visonic#3]
Hi

I'm new to HA and I'm trying my best to understand this component.
Im trying to follow the new instructions according to your update 0.1.0.

Questions:
1. In HA and in configuration.yaml should I still use the following code?
visonic:
  device:
    type: ethernet
    host: '192.168.1.128'
    port: 7523
  motion_off: 120
  language: 'EN'
  force_standard: 'no'
  sync_time: 'yes'
  allow_remote_arm: 'no'
  allow_remote_disarm: 'no'
  override_code: '1234'
  arm_without_usercode: 'yes'
2. If so, shouldnt I have a visonic.py in my custom_component folder? HA complains that the component missing. Cant find it in in the new update (0.1.0)?
3. I have a powerlink 3 using TCP to connect to the visonic. Is it possible, or do I need to buy any extra components?

Thanks for you effort and I hope you can help me.

**Comment by davesmeghead** [comment]
Ah that's OK, I'm sure I can help you. Have you seen the HA thread that's associated with this Component, please check it out [here](https://community.home-assistant.io/t/visonic-powermax-and-powermaster-component/55949/209)

So, on to your specific questions.
1. Yes, although you've missed the indentation, I assume that it's just a format thing in this comment
2. You need to update your HA to the latest version. With the latest version of HA, the Components all have their own directory within custom_components
3. I think this is going to be your main problem. This Component doesn't and can't use the powerlink modules. The powerlink hardware modules interact with the alarm panel and give a completely different interface. You'll need to buy either the ethernet/rs232 or usb/rs232 hardware that I suggest, sorry if this is confusing

Best of luck
