### ISSUE TITLE
visonic PIR sensor seen as a vibration

### ISSUE THREAD

**Issue by g4seb** [davesmeghead/visonic#31]
Hi,
thanks for your work. I have a problem. i have 2 PIR and 1 magnet. But 1 PIR seen as vibration sensor (Z01).

This is my log file : https://pastebin.com/pAb33C1Z

Thanks

Seb

**Comment by davesmeghead** [comment]
I have updated the code base to include the missing sensors. I have also updated it to be more explicit about PowerMax sensor types.  See github release 0.6.8.0
