### ISSUE TITLE
"DEF COMM" message in Powermaster33

### ISSUE THREAD

**Issue by domtik** [davesmeghead/visonic#33]
Hello,
First i want to thank you for this great Visonic integration. It is working perfectly with my Powermaster33. I was happy with it even before Powermaster33 was listed in the supported pannels but now it is even better :)
There is one error message that persists on the panel but does not seem to alter the fuctionality of the integration.
This message is "DEF COMM". I've a French panel and this means "communication failure". 
I'm using the Ethernet Module USR-TCP232-E2. Before i had the powerlink 3 and never got this error message.
When i enter the installer mode then quit the message disappears for a while than appears again.
Do you have an idea how to get rid of this message? 
Cheers

**Comment by davesmeghead** [comment]
The "communication failure" error may mean a lot of different things and not just about the powerlink3.  
Do you have telephone numbers set up in your panel? 

For the following you can look at the attributes of the alarm Entity in Home Assistant:
Do you have "Report to Central Station" enabled when it should be disabled? 
Do you have "Two-Way Voice To Central Stations" enabled
