### ISSUE TITLE
Wrong date and time format (FR Powermaster33 panel)

### ISSUE THREAD

**Issue by domtik** [davesmeghead/visonic#34]
Hello,

I tried today the service to export the event log. I could generate the csv file however something is wrong with the time and date format. Is there some option that i missed in the configuration other than "FR" for the French language?

Here is an extract from the file panel_log.csv (Powermaster 33):
current, total, partition, date, time, zone, event
1, 50, 1, 135/92/2110, 231:180, User 02, Désarmement
2, 50, 1, 135/92/2109, 124:80, User 03, Armement Total
3, 50, 1, 134/92/2095, 161:112, User 03, Désarmement
4, 50, 1, 134/92/2094, 148:175, User 03, Armement Total
5, 50, 1, 131/92/2047, 240:11, User 03, Désarmement
6, 50, 1, 130/92/2045, 155:182, User 02, Armement Total
7, 50, 1, 129/92/2033, 162:185, User 02, Désarmement

Best regards

**Comment by domtik** [comment]
One more thing, i can't find the xml file (supposed to be in the same folder as the csv file) and there is the following message in the notification area of Home assistant:
=============================
Visonic Alarm Panel
Panel Event Log - Failed to write XML file

**Comment by domtik** [comment]
Sorry for the text formatting. I dont know how i managed to write it so big :)

**Comment by domtik** [comment]
One more thing, i can't find the xml file (supposed to be in the same folder as the csv file) and there is the following message in the notification area of Home assistant:
Visonic Alarm Panel
Panel Event Log - Failed to write XML file

**Comment by davesmeghead** [comment]
So first of all I've looked at the event log issue.  The data format from your panel is very different to the format that I expect and I do not know what the data from your panel actually means.  If I take a snapshot of yours:
2021-05-11 20:03:01  [handle_MsgTypeA0] Packet = fb 02 01 8c 10 89 5c 7e 62 52 43

And now a snapshot of mine
2021-05-11 22:54:24  [handle_MsgTypeA0] Packet = fb 02 01 13 15 09 05 15 1f 55 43 
The "13 15 09 05 15" are hex values of minutes, hours, day of month, month of year and lastly the year from 2000
     When decoded this is    time=21:19    date=09/05/2021

Yours does not decode the same
I then wondered if it contains a representation of epoch time i.e. the time from midnight on 1/1/1970.  Using 8c 10 89 5c from yours and in reverse (little endian) would be a 32 bit value 5c89108c.  Converting this to epoch time would be:
Wednesday, 13 March 2019 14:15:40
So clearly this is also wrong but it is closer but still over 2 years wrong (unless you have the wrong time set on your panel).

Does the zone and event data from the event log look OK in the csv file? e.g. "User 02, Désarmement"
If it is then I can only assume that the values e.g. "8c 10 89 5c 7e" somehow decode to a date and time.  The 5c value (92 decimal) is in all entries so must represent the year or the leading value of something.

So, I don't know what to do next.  Perhaps I think about it a bit longer.

On the sensors and the MC-302 I would need to see a full HA log file, or at least the first 1500 or so lines. This way I can determine the sensor types and what they are supposed to be.  If you then tell me what model numbers they are I can associate them in the code for the next code release. 

And lastly, the xml file.  Again I would need the HA log file entries at the end of the log file section to tell me the reason why it is not being generated.  
You can try this: copy the "visonic_template.xml" file in to the same directory as your HA config files i.e. where configuration.yaml is located.

**Comment by domtik** [comment]
You can find the full HA debug log here: https://pastebin.com/jNCgxMT8. 
It was captured on 13 May at 23:13 CET and i checked that the panel date and time are good.
After copying the "visonic_template.xml" file into the HA directory and trying to export the event log, the file "panel_log.xml" is now generated in the same folder as the "panel_log.csv" file and there is no error in the notification area. 
The zone and event data from the event log look good so I think there is only a decoding problem of the time & date like you said.
Sensor types:
stype=Magnet should be "MC-302V"
stype=Motion should be "NEXT"
stype=Unk 7 should be "TOWER-32AMK9"
Thank you

**Comment by Sudo-Rob** [comment]
Is there a way to check to see if time is monotonic?  If it's non-monotonic, it might be encrypted to prevent spoofing.

This might be useful:

[https://en.wikipedia.org/wiki/ISO_8601](https://en.wikipedia.org/wiki/ISO_8601)

**Comment by domtik** [comment]
Yes the panel time was adjusted (I dont remember if it was one or two hours) between the samples but for sure not 2 days. I tried different calculaction methods with different offsets but no luck so far.

**Comment by Sudo-Rob** [comment]
It's possible I made an error.  I used this converter:  [https://www.epochconverter.com/](https://www.epochconverter.com/). It's best to set a preference for 24-hour format and assume everything is GMT.  Otherwise, it might pick up a local offset using IP geolocation.

**Comment by davesmeghead** [comment]
I've kept going back to it over the past week or so and I can't work out a pattern to decode the date and time.  
Since that start of the log file event log download it has

**Comment by nlrb** [comment]
You're right with epoch time for PowerMaster.
Take as an example: 0d a0 fb 05 01 07 da e7 62 a7 42 1b 43 e8 0a
Date/time is in bytes 6, 7, 8, 9.
I.e. 0x62e7da07 = 1659361799 = GMT: Monday, 1 August 2022 13:49:59

**Comment by davesmeghead** [comment]
Thanks for spotting that and for the info, it's very much appreciated.
I recently bought a PowerMaster 30 Panel from Ebay and was planning to take a proper look at it as I have a PowerMax Pro.  
I think I've fixed the issue in the release I've just uploaded, release 0.8.0.0.  Give it a try and if it's OK then we'll close this issue.

**Comment by davesmeghead** [comment]
I'm assuming that this issue is fixed as no further feedback.
