### ISSUE TITLE
No ‘version’ key in the manifest file for custom integration ( HA 2021.3.0 )

### ISSUE THREAD

**Issue by drmule** [davesmeghead/visonic#35]
https://community.home-assistant.io/t/no-version-key-in-the-manifest-file-for-custom-integration-ha-2021-3-0/286487

**Comment by davesmeghead** [comment]
Sorry but yes there is, [here's the manifest file](https://github.com/davesmeghead/visonic/blob/master/custom_components/visonic/manifest.json)

The version key is there. 
Also that is the March release of HA, I suggest you update your HA release and are you using the latest version of this integration?
