### ISSUE TITLE
Abnormal system memory consumption

### ISSUE THREAD

**Issue by fguerzoni** [davesmeghead/visonic#36]
Hi,
I'm running the latest integration version: 0.6.8.2 on Home Assistant 2021.5.4
I noticed that when the visonic integration is running the HAss instance crashes  with an out of memory error type after (more or less) one day.
The instance runs on an old orange pi with 1GB memory, but I don't think it's an issue because when it starts fresh it use less than150MB.
When it's running you could observe a slow but constant increase of memory consumption.
I didn't notice that when I experimented with the Visonic integration at the start of Jan this year.
I suspect that there is a kind of memory leak in the Visonic integration that keeps consuming the available memory.
What do you tihink?
Thanks and regards

**Comment by fguerzoni** [comment]
Cannot replicate the issue. I will continue to monitor it.

**Comment by davesmeghead** [comment]
OK.
I don't really allocate memory from python and python itself has its own garbage collection so memory leaks/errors are rare. I don't really store anything other than data from the EEPROM when the integration first starts. 
Please continue to monitor it as you say.

**Comment by fguerzoni** [comment]
Cannot reproduce it. I close the issue and I'll continue monitoring it on my side.
