### ISSUE TITLE
Wrong sensorType detected

### ISSUE THREAD

**Issue by fguerzoni** [davesmeghead/visonic#38]
Hi,
I'm running the "version": "0.6.8".
I noticed that a magnetic switch (i=1) is detected as a smoke sensor when actually, seen from the outside, looks like the sensor with id=1 and id=2.
Could you please check the following logs?

```
We're almost in powerlink mode *****************************************
Process Settings from EPROM
 pmPanelTypeNr 1 (1)    model PowerMax+
 Processing settings information
 Processing settings - panel code index 012F
      i=0 :    SensorID=0x95   zoneInfo=0x7   ZTypeName=Perimeter   Chime=Off   sensorType=1   zoneName=Front door
      i=1 :    SensorID=0x7a   zoneInfo=0x7   ZTypeName=Perimeter   Chime=Off   sensorType=4   zoneName=Garage door
      i=2 :    SensorID=0x85   zoneInfo=0x7   ZTypeName=Perimeter   Chime=Off   sensorType=1   zoneName=Back door
      i=3 :    SensorID=0xe3   zoneInfo=0xc   ZTypeName=Interior   Chime=Off   sensorType=0   zoneName=Downstairs
      i=4 :    SensorID=0xd5   zoneInfo=0xc   ZTypeName=Interior   Chime=Off   sensorType=0   zoneName=Upstairs
      i=28 :    SensorID=0xff   zoneInfo=0x17   ZTypeName=Perimeter   Chime=Melody   sensorType=3   zoneName=Upstairs
      i=29 :    SensorID=0xff   zoneInfo=0x17   ZTypeName=Perimeter   Chime=Melody   sensorType=3   zoneName=Upstairs

```

```
=============================================== Display Status ===============================================
  key 0  Sensor id=1  dname=Z01  stype=Magnet   zname=Front door     ztypeName=Perimeter  ztamper=0  ztrip=0  bypass=0  lowbatt=0  status=0  tamper=0  enrolled=1  triggered=0 
  key 1  Sensor id=2  dname=Z02  stype=Smoke    zname=Garage door    ztypeName=Perimeter  ztamper=0  ztrip=0  bypass=0  lowbatt=0  status=0  tamper=0  enrolled=1  triggered=0 
  key 2  Sensor id=3  dname=Z03  stype=Magnet   zname=Back door      ztypeName=Perimeter  ztamper=0  ztrip=0  bypass=0  lowbatt=0  status=0  tamper=0  enrolled=1  triggered=0 
  key 3  Sensor id=4  dname=Z04  stype=Motion   zname=Downstairs     ztypeName=Interior   ztamper=0  ztrip=0  bypass=0  lowbatt=0  status=0  tamper=0  enrolled=1  triggered=0 
  key 4  Sensor id=5  dname=Z05  stype=Motion   zname=Upstairs       ztypeName=Interior   ztamper=0  ztrip=0  bypass=0  lowbatt=0  status=0  tamper=0  enrolled=1  triggered=0 
  key 28 Sensor id=29 dname=Z29  stype=Wired    zname=Upstairs       ztypeName=Perimeter  ztamper=0  ztrip=0  bypass=0  lowbatt=0  status=0  tamper=0  enrolled=1  triggered=0 
  key 29 Sensor id=30 dname=Z30  stype=Wired    zname=Upstairs       ztypeName=Perimeter  ztamper=0  ztrip=0  bypass=0  lowbatt=0  status=0  tamper=0  enrolled=1  triggered=0 
Model PowerMax+              PowerMaster No                     LastEvent None                   Ready   Yes          
Mode  Powerlink              Status      Disarmed               Armed     No                     Trouble None              AlarmStatus None      


```

**Comment by davesmeghead** [comment]
Hi,
If you tell me what the sensor type 0x7a is when reported from the panel (Zone Z02) then I'll add it as a sensor in the code.
It's a magnetic sensor but what is the model name?

**Comment by fguerzoni** [comment]
I expected to find a MCT-302 because the sensor Z02 is identical from the outside to Z01 and Z03.
Instead I found a MCT-550 Flood Detector (as reported by the attached picture) which I was not aware to have bought and in any case it's not a smoke detector.
Thank you very much

![IMG-20210614-WA0000](https://user-images.githubusercontent.com/19572856/121899098-614ec100-cd24-11eb-9018-d159b76c00de.jpg)

**Comment by davesmeghead** [comment]
I have assigned visonic device type A7 to be a MCT-550 Flood Detector and it will be uploaded in the next release I make.

You will have to override the device class in Home Assistant as per [this section on the wiki](https://github.com/davesmeghead/visonic/wiki#home-assistant-device_class) so the next release won't make any difference to you, sorry.

**Comment by davesmeghead** [comment]
I have just released a new version that includes A7 as a MCT-550, but it's likely you will need to override the device_class in the Home Assistant configuration to get yours to display correctly.
I'll close this thread and thanks for your help.

**Comment by fguerzoni** [comment]
@davesmeghead 
I had the time to test the latest release which works pretty fine. Thank you.

MCT-550 has 2 outputs that need to be registered as they would be 2 different devices:
- a magnet sensor
- a flood sensor

So it isn't totally coherent the definition you assigned to  the first output of A7:

```
[custom_components.visonic.pyvisonic]      key 8  Sensor id=9  dname=Z09  stype=Flood    zname=Custom 1       ztypeName=Perimeter  ztamper=0  ztrip=0  bypass=0  lowbatt=0  status=0  tamper=0  enrolled=1  triggered=0 
[custom_components.visonic.pyvisonic]      key 9  Sensor id=10 dname=Z10  stype=Flood    zname=Custom 2       ztypeName=Flood      ztamper=0  ztrip=0  bypass=0  lowbatt=0  status=0  tamper=0  enrolled=1  triggered=0 
```

I applied your suggestion to edit the customize.yaml so to add the correct type and it works.
```
"binary_sensor.visonic_z09":
  friendly_name: 'Test magnet'
  device_class: door
"binary_sensor.visonic_z10":
  friendly_name: 'Test flood'
  device_class: moisture

```
![Screenshot from 2021-06-25 20-12-00](https://user-images.githubusercontent.com/19572856/123468208-c42c3c00-d5f1-11eb-9fdb-a1c5a501eeef.png)
