### ISSUE TITLE
alarm_panel_reconnect service causes alarm_control_panel.visonic_alarm state to unavailable

### ISSUE THREAD

**Issue by haforme** [davesmeghead/visonic#39]
I'm running integration version 0.6.8.2 with a PowerMax+ alarm panel. The integration negotiates to the "Standard Plus" mode.
HA and HA OS are the latest versions.

If I call the service "Visonic Intruder Alarm: alarm_panel_reconnect" the state of "alarm_control_panel.visonic_alarm" turns to "unavailable" and stays there.

The only way I can recover from it is to restart Home Assistant.

It worked fine in the previous version. Thank-you.

**Comment by davesmeghead** [comment]
Hi,
Have you tried manually enrolling again from your panel, do this between 2 and about 5 minutes after restarting Home Assistant. 
I'd be interested in 2 log files (with the appropriate logger settings as per the wiki)
1. After a restart of HA, including the time for you trying to manually enroll so about the first 10 minutes.
2. Just before and after you try calling the ```visonic.alarm_panel_reconnect``` service

If you upload the log files to pastebin/dropbox and leave a link here, thanks. Even if manually enrolling works then please do the 2nd one anyway.

**Comment by davesmeghead** [comment]
I have been testing the restart service and I was occasionally able to repeat what you are seeing. I believe I have fixed it and I've released a new version as 0.6.9.0 so please give it a try.
If you are still struggling on getting in to Powerlink Mode then please let me know.

**Comment by haforme** [comment]
That resolved the problem. Thank you so much! Your integration works like a champ.
