### ISSUE TITLE
Ask about MQTT control

### ISSUE THREAD

**Issue by JMAnguita** [davesmeghead/visonic#4]
Any suggestion about how to control via MQTT the alarm entity created with your component?

**Comment by JMAnguita** [comment]
I reply myself. I's easy:

On the master's configuration.yaml:
`alarm_control_panel:
  - platform: mqtt
    name: PowerMax Pro
    state_topic: "slave/alarm_control_panel/visonic_alarm/state"
    command_topic: "slave/alarm_control_panel/visonic_alarm/set"`

On the slave's configuration.yaml:

`mqtt_statestream:
  base_topic: slave
  publish_attributes: true
  include:
    domains:
      - alarm_control_panel
      - binary_sensor`

On the slave's automation.yaml:

`- alias: Armado TOTAL remoto
  trigger:
    platform: mqtt
    topic: slave/alarm_control_panel/visonic_alarm/set
    payload: 'ARM_AWAY'
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.visonic_alarm`

... and so on with all states.

Thank you VERY MUCH for your component.

**Comment by davesmeghead** [comment]
Thankyou for describing how to set it up, I'm closing this issue
