### ISSUE TITLE
Home assistant cannot see Wemos with Esp-Link

### ISSUE THREAD

**Issue by neilma1** [davesmeghead/visonic#40]
Hi Dave,
Firstly - Thank you! Been using your software for a couple of years with no issues. However this week, had to move my alarm box and ended up breaking my USR TCP232 device (long story !). Anyway, i had a couple of Wemos, Nodemcu D1 Mini's lying around and so I went about installing Esp-link on one as per your instructions. Got it all set up - Connected to my home network and played with the baud rate (9600 and 38400) however whatever I try, I cannot get HA to see the alarm box.
I have removed and reinstalled the HACs component, deleted the integration etc. Rerun the install (I chose Ethernet) and then the IP of the Esp-link (however, and this is finally my question) I was entering the same port I have always used (from when I used to have it configured in the Config.yaml file. Is that the right port to use? Where else would I set the port (if need be) in esp-link? I am wondering if this is the issue and what default port I should use?

I have only had a couple of random characters show up in the microconsole on the esp-link - not sure if thats related? I have tried using the pins on the alarm and have also soldered onto the pads - still the same issue. HA cant see it :(

Anything else I should try? (Panel is a PowerMax Pro if that makes any difference)

thx
Neil

**Comment by davesmeghead** [comment]
Hi,
Sounds like you're nearly there
Have you tried setting the port to 10077 in the Integration.  
This is defined on the wiki [here](https://github.com/davesmeghead/visonic/wiki/Using-Wemos-and-ESPHome#install-visonic-integration-in-to-home-assistant)
The Ethernet address is the Static IP you put in secrets.yaml
The baud rate should be the same as you used before, for your panel model that's probably 9600, you set this in secrets.yaml
Hope you get it working but let me know 👍

**Comment by neilma1** [comment]
Hiya - thanks for the quick reply!

I tried 10077 but I was following the steps on here https://github.com/davesmeghead/visonic/wiki/Using-NodeMCU-PowermaxProModel6 which is what I am using - not the ESPHome version on a Wemos.

I couldnt find any mention of a port on this page - https://github.com/davesmeghead/visonic/wiki/Using-NodeMCU-PowermaxProModel6  or where to set it?

Thx again!
Neil

**Comment by neilma1** [comment]
Oh - I did already try ports 23 and 2323 as mentioned in the esp-link documentation - They didnt work either :(

**Comment by davesmeghead** [comment]
It defaults to port 6638 but I override that to 10077.
Try it with port 6638 please
The default of 6638 is set in stream_server.h near the bottom of the file

**Comment by neilma1** [comment]
Thanks Dave - will give that a go. Is there any way to check if the pins on the back of the alarm are sending anything (I dont have a scope but have multimeters etc if that helps?) - Just wondering why the microconsole is always showing blank so wondering if there is nothing being sent from the alarm? 

Interestingly the alarm still has the BBA Comm Lost error on the screen even after removing the wemos - is there a setting I had to change in the alarm to turn anything on or will that go eventually (have tried going in and out of installer menu)

**Comment by davesmeghead** [comment]
Without a logic analyser or scope I don't there's any way to tell for certain.

I don't usually advertise but I bought one of these
https://www.amazon.co.uk/Hobby-Components-24MHz-Analyser-1-1-16/dp/B00DAYAREW/ref=sr_1_7?dchild=1&keywords=saleae&qid=1625909050&sr=8-7

It's a cheap logic analyser and the free software will decode RS232, it works pretty well but I wouldn't use it for high frequency stuff.  9600 Baud is well within its specs though.  The panel doesn't volunteer data though, most of the time it needs to be sent a message and then I get a reply, so I've connected it to the gadget I'm using but then also attach the logic analyser to both Rx and Tx to see what is going in and out of the panel.

For the Comm Lost error there's should be a menu setting to tell the panel that you have removed the powerlink device.

There's 1 thing that you can tell me though. Please look at your log file
If it has this in it
```
Setting TCP socket Options Exception [Errno 111] Connection refused
Failed to connect into Visonic Alarm. Check Settings.
```
Then you have the wrong IP address or the wrong port

If you have this
```
[Controller] Visonic Plugin has suspended all operations, there is a problem with the communication with the panel (i.e. no data has been received from the panel)
```
Then an Ethernet connection has been made to the Wemos but my integration is not receiving any data.

It's almost certainly going to be 1 of these 2 cases, please let me know

**Comment by davesmeghead** [comment]
One more thing.  I have introduced a loopback test that may be useful for you.
Note that I have updated the release on Github so please download this latest version. 

Please see here for more info
https://github.com/davesmeghead/visonic/wiki#loopback-test

**Comment by neilma1** [comment]
Thanks Dave

I will give it a go tomorrow and test the loopback too.

Thanks again for the great support!

(Ive also purchase another TCP device but that may be a few weeks to come from china but hopefully I can get the wemos working in the meantime....

Will let you know as soon as I have something to share...

Cheers
N

**Comment by neilma1** [comment]
Ok - I have now gone through 3 Wemos D1 Mini's!  Installing ESP-Link seems to go ok, I access the webpage, change the SSID, disable the ports etc, then they either dont reconnect to the new SSID or they do and then only one of my other PC's can connect it. Which leads me to believe that either esp-link isnt being set up correct (as I get the same issue on 3 different Wemos) or there is something funky going on my network . I tried the loop back but as I am not confident that the device is sitting on the network correctly then I am not sure we will get anything from that.

So my next plan is that I have a Pi Zero lying around - Will get Ser2net installed on that and report back!

**Comment by davesmeghead** [comment]
I'm a little confused, if you follow my ESPHome wiki instructions [here](https://github.com/davesmeghead/visonic/wiki/Using-Wemos-and-ESPHome) then you shouldn't need to reconnect, access web pages, change/set SSID etc.  
All settings are set in the secrets.yaml file (apart from the port number).  You only need to connect the Wemos by USB to your PC the first time and after that it should do "over the air" updates on wifi.

**Comment by neilma1** [comment]
Hiya

I haven't been setting up that type of wemos - I have been using Wemos D1 Minis and using the instructions here under the Ethernet Option 2
Using NodeMCU PowermaxProModel6 * davesmeghead/visonic Wiki (github.com)<https://github.com/davesmeghead/visonic/wiki/Using-NodeMCU-PowermaxProModel6>

I have a TTL to USB lead arriving today so will try the Pi Zero with it and see how we get on....

**Comment by neilma1** [comment]
Hey Dave
So just to close this off - I am all back up and running using the Pi Zero W and a TTL to USB cable. 
I still have the USR TCP232 replacement winging its way over from China as thats my preferred choice as I can house everything in the alarm box without having to run separate power for the Pi etc. Thanks again for your help and suggestions (and the great integration too!) - Shout if I can help with any testing etc or anything to help.

Cheer
Neil
