### ISSUE TITLE
How does the motion detectors actually works?

### ISSUE THREAD

**Issue by zyberzero** [davesmeghead/visonic#42]
Hi! Thanks for this integration. So far it has worked pretty well for me.

However, I do have a question regarding how the motion detectors work. 

It seems to me that when it triggers the first time, it sets the binary_sensor as detected for the amount of time set in the integration, no matter the time some one actually disturbed a zone (example: I have one detector in my home office. but it only detects me for the defined time even though I'm in the office for much longer time than that. 

I've enabled all debug logging but I can't see any event from when the detector is in clear state. Doesn't Visonic do that? Does it only sends the first time it trips and nothing else until it is triggered again after being idle for two minutes? 

I'm using a Powermax Complete v1 with Next T MCW, and integrating using a Wemos-clone connected to the panel.

Thanks again!

**Comment by davesmeghead** [comment]
Hi,
I think that the best thing I can do to help is start with what the panel tells me:
- Every Non-PIR sensor the panel sends "Zone Open" and "Zone Closed"
- Every PIR sensor the panel sends "Zone Violated"

The panel also tells me about tamper and battery state etc but they aren't relevant here.

**For every Non-PIR sensor:**
- "Zone Open" I set "triggered" and "open" to True
- "Zone Closed" I set "triggered" and "open" to False
- From setting "triggered" to True, if the time elapses past "Motion Off Delay Time" then I set "triggered" to False

Notes:
- That "Motion Off Delay Time" is the configuration setting and that "open" remains True
- The Binary Sensor in Home Assistant shows "triggered" or "open".  So as long as the Zone is Open then the sensor status in HA will show "open" (as the device class is set to door or window)

**For every PIR sensor:**
- "Zone Violated" I set "triggered" to True
- From setting "triggered" to True, if the time elapses past "Motion Off Delay Time" then I set "triggered" to False

Notes:
- That "Motion Off Delay Time" is the configuration setting and that "triggered" remains True
- The Binary Sensor in Home Assistant shows "triggered" or "open".  So as long as the Zone is Open then the sensor status in HA will show "violated" (as the device class is set to motion)

**Visonic Operation**
Each PIR sensor has a timeout period.  The PIR sensor will detect motion and then not report motion detections for a period of time. This time is a setting inside the sensor itself and some PIRs allow you to select this by changing a pin position on the little PCB for the sensor itself. 

** Home Assistant Operation **
PIRs will be triggered on the lowest time period, either the PIR setting itself or the "Motion Off Delay Time".  I set "Motion Off Delay Time" to 120 seconds as I do not want repeat PIR triggers within that time. 

Hope this helps

**Comment by codechippy** [comment]
Hi Dave
have just got this going on my Home Assistant instance and it works like a charm, many thanks for this integration.
I noticed in you comment above that you get the battery status for sensors, but ignore, any chance we can get this inside Home Assistant.
I recently had an issue while I was away from home when a sensor failed due to low battery and was setting off false alarms
so would be good to know when I need to change battery ahead of time.

Many thanks
CodeChippy

**Comment by anthonywalker75** [comment]
I use a flow in NodeRed to check the battery states every day and if 1 or more is low it sends a notification, it also sets an input flag true which causes an entities panel to display which shows all the sensor battery states.

Happy to share code if requested.

Anthony

**Comment by codechippy** [comment]
Hi Anthony
that would be great

CodeChippy

**Comment by davesmeghead** [comment]
You can also use an Automation within Home Assistant. Creating an Automation using multiple triggers, 1 for each sensor, use the Battery Level Attribute of each Sensor Entity. Don't fill in the "From" field, just use the "To" field and set to 0.

**Comment by anthonywalker75** [comment]
[Visonic Battery Status - NodeRed.txt](https://github.com/davesmeghead/visonic/files/7118068/Visonic.Battery.Status.-.NodeRed.txt)

Node red flow to monitor battery levels. Checks every morning at 1am. if any sensor doesn't have 100 as value sets mqtt flag to true and email's & notifies my mobile.

The mqtt flag is then used to display an entities panel in lovelace showing the battery values.

This could be done using a HA automation but i find things make more sense using node red.

Anthony
