### ISSUE TITLE
Alarm status when disabling alarm

### ISSUE THREAD

**Issue by phoenix-blue** [davesmeghead/visonic#43]
Hi,

When I turn of my alarm (powermax pro) I get sometimes an notification that I have an active alarm at the moment I turn of the system.
Is there a way to see if this is coming from the alarm panel?

Because HA use the panel status to run some additional scripts in case if there is an active alarm.

![Screenshot_20210727_181152_io homeassistant companion android](https://user-images.githubusercontent.com/13711891/127193153-ad220ac8-34b9-4f35-a45d-336647984c08.jpg)

**Comment by davesmeghead** [comment]
Hi,
Are you getting to Powerlink Mode or Standard Plus or Standard?
Look at ```alarm_control_panel.visonic_alarm``` and the "Panel Mode", this is mine for example
![image](https://user-images.githubusercontent.com/10319422/127232623-d64d3933-f2f7-4ba5-9212-b09296d92f82.png)

To find out more I'll need you to upload a Home Assistant log file to pastebin or dropbox and post a link here please so I can take a look through. I do say this on the forum page [here](https://community.home-assistant.io/t/visonic-powermax-and-powermaster-integration/316702). Please remember to set your logger settings according to my instructions.

**Comment by davesmeghead** [comment]
As this is over 2 months old I am closing the issue.
