### ISSUE TITLE
Panic Button in HA

### ISSUE THREAD

**Issue by VladimirMakaev** [davesmeghead/visonic#44]
I've recently connected my PowerMax Express alarm to HA. Everything works great so far. I was amazed that everything even connected to my Apple Home Kit via Home Assistant Bridge which is impressive.

I was looking for a possibility to have a software "panic" button that can be triggered through HA automation from a non-Visonic sensor for instance. Or via Apple Home Kit automation since the alarm is added to it via bridge.

Is this available in any shape or form with current plugin? Do you know if PowerLink protocol supports turning on the siren?

**Comment by davesmeghead** [comment]
Hi,
I'm sorry but it is not *directly* supported, there is no way to trigger the panels internal or external siren from the integration.  
However, if you can use a Wemos D1 R2 device and install ESPHome on it then you can use the ESPHome integration in Home Assistant to control a relay that is located inside you panel.  You may be able to use this relay with a wired sensor or panic input in your alarm panel.  The downside of this is that the Wemos is a wifi device on your home network which in my limited experience of them seems to be less reliable than wired connections and it does seem to suffer from wifi dropouts. I went back to my wired device.
It is described further [here](https://github.com/davesmeghead/visonic/wiki/Using-Wemos-and-ESPHome#using-wemos-d1-r2-and-you-can-trigger-the-siren) on the wiki.

**Comment by VladimirMakaev** [comment]
Thanks for the reply and amazing plugin!
