### ISSUE TITLE
No data recieved after a couple of hours / days

### ISSUE THREAD

**Issue by skalman77** [davesmeghead/visonic#47]
Home assistant is stop working after a period, can be hours or sometimes a couple of days. The panel is reporting error and the orange lamp is lighting up.

Home assistant is reporting:

[Controller] Visonic Plugin has suspended all operations, there is a problem with the communication with the panel (i.e. no data has been received from the panel)

I using a ESP8266 for connecting to the panel via WiFi with software ESP-link.

How can i keep the panel connected? 

To get it working again, i have to restart home assistant and alarm panel.

**Comment by davesmeghead** [comment]
I suspect that the integration has detected a failure in the communication and then restarted itself, but after the restart it didn't restore the communication. Have you looked at the troubleshooting section on the wiki
https://github.com/davesmeghead/visonic/wiki#troubleshooting
