### ISSUE TITLE
feature req: add support for visonic TOWER-32AM PG2

### ISSUE THREAD

**Issue by chrisns** [davesmeghead/visonic#50]
Hi, the motion sensor https://www.visonic.com/Products/PowerG-Wireless-Property-Protection/tower-32am-pg2 currently shows as a model as `unknown` in HA and a generic binary sensor class, should be a `motion` class

happy to raise PRs if you could point me in the right direction, I couldn't obviously see where the change would be needed in the codebase

**Comment by davesmeghead** [comment]
Hi,
Can you please set your Home Assistant logger settings like [this on the wiki](https://github.com/davesmeghead/visonic/wiki#logger-settings) and look at the Home Assistant log file. You will find an entry similar to the following for each of your sensors:
```
[Process Settings]      i=0 :    VisonicSensorRef=0xe4   zoneInfo=0xc   ZTypeName=Interior   Chime=Off   SensorType=Motion   zoneName=Kitchen
```
I need to know:
- the value of VisonicSensorRef for the unknown sensor and
- the sensor type (and not just glass break detector). I need the make and model number to get it accurate, preferably a http link to the device.
- Whether you have a PowerMax or PowerMaster panel type

I'll then set the sensor up better in HA, including the device class to Safety
That's all for now.

**Comment by chrisns** [comment]
2022-01-14 23:15:35 DEBUG (MainThread) [custom_components.visonic.pyvisonic] [Process Settings]      i=14 :    VisonicSensorRef=0x6   zoneInfo=0xc   ZTypeName=Interior   Chime=Off   SensorType=Unknown   zoneName=Garage

PowerMaster 30

https://www.visonic.com/Products/PowerG-Wireless-Property-Protection/tower-32am-pg2

**Comment by davesmeghead** [comment]
This will appear correctly in the next release.
Thanks

**Comment by chrisns** [comment]
please could you advise a paypal/github sponsors/something so I can buy you a beer/coffee? :)
(or a preferred charity)
thanks!!
