### ISSUE TITLE
feature req: allow shock sensor SD-304 PG2 to be configrable to door/window/garage like other contact sensors

### ISSUE THREAD

**Issue by chrisns** [davesmeghead/visonic#51]
Hi, would be great if the shock sensor https://www.visonic.com/Products/PowerG-Wireless-Property-Protection/sd-304-pg2 could be configurable to say its a door/window/garage sensor like the other contact sensors

happy to raise PRs if you could point me in the right direction, I couldn't obviously see where the change would be needed in the codebase

**Comment by davesmeghead** [comment]
This is not something that I wish do add as a code change or capability, sorry. The only option to do this is to allow the user to manually set them in the integration somehow.
See [here ](https://community.home-assistant.io/t/how-to-customize-device-class-in-hass-2021-12/365934) about the HA discussion about this.

**Comment by chrisns** [comment]
Thanks so much for the reply.
Maybe taking cross purposes, it doesn't show the "show as" field that is described in that post like it does for other contact sensors

**Comment by davesmeghead** [comment]
If that's the case then I suggest that you use customize.yaml

From configuration.yaml include this line
customize: !include customize.yaml

And then in customise.yaml you'll need something like this to make the device class a door
binary_sensor.visonic_z01:
  device_class: door

**Comment by chrisns** [comment]
digging through the code a bit with clues from the logs from my other tickets
https://github.com/davesmeghead/visonic/blob/b5f6ed7cc917f2ceb29fe1d98024964d7d2e2c95/custom_components/visonic/binary_sensor.py#L149-L150
appears to be the key point.

I wonder does that mean the sensor will only report open when the vibration is triggered, or is it on the reed switch, or either??
also for sensors that also have an aux, is it possible to expose each sensor input as separate entities within the device?

Very happy to pick this up as a thing and PR, just wondering what you've seen or if you'd already ruled it not possible?

**Comment by davesmeghead** [comment]
I'm not sure what you're trying to achieve here.  It's easy for you to override the device class if you don't like the default that I set, you do this by using the customise.yaml file (as per my previous suggestion).  The valid device classes are on the HA [here](https://www.home-assistant.io/integrations/binary_sensor/).

The shock sensor works by vibration and so the closest device class within HA is vibration i.e. the sensor has been triggered and when it does it indicates vibration. That is why I default the device type to vibration but as I said, you can override that if you want to.

I've tried to work out from other peoples log files to get devices with multiple sensors to work.  I have a PowerMax panel and those devices aren't supported so it's not something that I can try on my own panel.

**Comment by chrisns** [comment]
yeah, and really grateful for that pointer!

This sensor: https://www.visonic.com/Products/PowerG-Wireless-Property-Protection/sd-304-pg2
Has a vibration, contact and aux input sensor

So ideally if the panel can see the difference in which gets triggered I'd have three entities within the device.

I'll take one apart, short the sensors and sniff the traffic to try and see if the payload is any different when they're triggered. closing this issue for now, will report back when I've had a chance to fiddle

**Comment by davesmeghead** [comment]
I have suspected in the past that a PowerMaster panel sends "B0" messages for this kind of extra information.  In the config for the integration, go back in to configure the integration and you should now be able to enable B0 processing, see if you can correlate the activity from the sensor itself (your 3 entities) with the messages in the log file.
