### ISSUE TITLE
The integration says "no data has been received from the panel" but the panel is showing an update message

### ISSUE THREAD

**Issue by ekutner** [davesmeghead/visonic#54]
I'm trying to connect this integration to a PowerMax+ panel for the first time.
I'm using a ESP32 board for that and installed ESPHome on it. When I connect RX-TX in loopback the integration reports "LOOPBACK TEST SUCCESS". However, when I connect to the panel itself it gives the above message after just about 30 seconds.
While this is is happening the panel itself displays the message: "Updating Data" (my panel language is not English and I couldn't find a way to change it so I'm translating, but I assume it would be something along those lines). This suggests to me that the physical connection is correct and the problem may be somewhere else. As another validation I tried to change the baud rate on the ESP32 to 38400, with that rate the "Updating Data" message never appeared. So I'm pretty sure the physical connection is OK.

On the panel configuration side, I've changed the default Mast. DL Code from AAAA and configured that in the integration dialog. I don't have the Inst. DL Code option in my panel so didn't define that. Finally, I've enrolled the PWRLNK, I didn't do it while the integration was working because it just gives up so quickly, but the panel now says it is enabled.

I've also tried running the "simple_example.py" program separately, and it behaves exactly the same.

I'm not sure how to check my panel version. The only place I found something that looks like a version number is in the panel's serial number display and it says v3.4.08

The log file showing a few attempts is attached (I redacted my PIN codes).
[home-assistant.log](https://github.com/davesmeghead/visonic/files/8082565/home-assistant.log)

Any help would be greatly appreciated.

Thank you

**Comment by davesmeghead** [comment]
Given these
- Loopback test works
- Could "Updating Data" be "Downloading Data" instead?  I assume so as this would be the most likely panel message

I would say that sending data from HA to your panel is working and the panel receives the request to download the EEPROM.
However, I see this in the log file
```
[Controller] Visonic Plugin has suspended all operations, there is a problem with the communication with the panel (i.e. no data has been received from the panel)
```
This indicates that no data is being received in HA from your panel.  I suggest that you check your Tx on the panel to Rx on the ESP32 cable and connections, make sure you're usingthe correct pins and that the cable itself is OK.

**Comment by ekutner** [comment]
I've double checked everything, including replacing the wires, and it all seems fine. The only thing I can't be 100% sure about is that I'm connecting to the right TX pin on the panel. I've been using this pinout diagram:
![PowerMax+ Pinout](https://user-images.githubusercontent.com/5628151/154493394-02beeed2-5988-4678-b838-42441b761872.jpg) 
The RX and GND pins check out, so I can only assume the TX is also as indicated in the diagram. However, just to be sure, I tried looking for the TX pin by connecting to every other available pin. I manged to blow my ESP32 board by accidentally connecting it to a 12V pin but other than that no other pin works. I did notice though that pin 1 in the diagram gives a constant +5V, is that normal for a TX pin?

Any other suggestions how to troubleshoot it?

**Comment by davesmeghead** [comment]
I know this is going to be tricky but leave the gnd and Tx --> Rx connected and then restart the integration in HA to put the panel in to downloading state.  Measure the voltage on the panels Tx pin to see if it fluctuates from 5v.  It should be sending the EPROM data out of the panel so you should see voltage fluctuations on your meter. If it stays at 5v then it may be broken in some way.

**Comment by ekutner** [comment]
I'm powering the ESP32 with 5V from pin 11 in the diagram. 
If pin 1 from the above diagram is the right pin then it just doesn't work. To be honest I didn't try the test you suggested with the multimeter but I'm quite certain it doesn't sample nearly frequently enough to see 9600 fluctuations a second.

**Comment by ekutner** [comment]
My $20 multimeter didn't show any fluctuations, I'll see if I can get something better somewhere but closing this issue for now.
Thank you for your help.
