### ISSUE TITLE
Triggering Fire Alarm State from HA - Possible Feature Request

### ISSUE THREAD

**Issue by anthonywalker75** [davesmeghead/visonic#60]
Hello

My Visonic smoke detector recently gave up on me. (It permantly comes up with "Clean Me" on the panel despite having cleaned it).
I have looked to see if I can get another one and have discovered that they are either unavailable or prohibitively expensive.

My only recourse is to get an alternative unit either using zigbee, zwave or wifi, which will integrate with home assistant.

My question is this. Is there any way home assistant can trigger the "Fire" alert on the Visonic panel? (The same way as if somebody had pressed the button on the main panel to manually trigger it).

If this is not possible currently could this be submitted as a feature request for a future release.

My backup plan is to use a Shelly-1 or similar device with the relay connected to one of the wired sensor ports on the panel and that port programmed to the fire zone.

Regards

Anthony

**Comment by davesmeghead** [comment]
Hi,
There isn't a direct way that I or anyone else have found as far as I know.  I keep looking at other visonic integrations that people have done for other systems such as Vera but no one seems to know if there's a way to trigger the siren, or other controls such as the one you ask about.  It's already on my wish list to add in future but at the moment I do not know how to do it.

The opposite works, the panel tells the integration when the button is pushed but nothing that I know of to command it externally.

The only way that I have managed to trigger the siren is to use a relay on a wired sensor in the panel using a Wemos D1R2.
https://github.com/davesmeghead/visonic/wiki/Using-Wemos-and-ESPHome#using-wemos-d1-r2-and-you-can-trigger-the-siren

Regards
Dave

**Comment by davesmeghead** [comment]
I've added this to the dev build for PowerMaster Panels.
As far as I can see there is no way to do this for PowerMax Panels.
