### ISSUE TITLE
Powermax+ panel does not send "zone open" status

### ISSUE THREAD

**Issue by rhannink** [davesmeghead/visonic#61]
Hello,

Whenever I have a door open, I am not able to arm the alarm. The Powermax+ panel shows a "zone open" on its display.
Is it correct that this status is not sent to HA, so I can check for this status before I try to arm the alarm?

I can of courses check the status of the individual sensors, but getting the "zone open" status from the panel would me much more convenient.

Kind regards,

Remco

**Comment by gurbyz** [comment]
My Visonic integration gives my a `binary_sensor.visonic_alarm_problem_to_arm` sensor which tells me if I'm able to arm or not. If a window or door is open, this sensor reports a problem.
![image](https://user-images.githubusercontent.com/3920372/179047978-683af3de-671e-41fe-a167-35ffc318980c.png)

**Comment by davesmeghead** [comment]
If you have a door open or sensor triggered then you will not be able to arm the panel unless you bypass that sensor.

"Panel Ready" is a Home Assistant Attribute of the Visonic Alarm Entity `alarm_control_panel.visonic_alarm`.  If "Panel Ready" is false (or No) then you will not be able to arm your panel.
