### ISSUE TITLE
Visonic integration trigger arming is only working for armed_away, not for armed_home

### ISSUE THREAD

**Issue by rhannink** [davesmeghead/visonic#64]
Hello,

I am using your great integration with a Powermax+ panel. everything works fine, only one automation which triggers when the panel is arming.
When I switch to **armed_away**, it triggers, but it does not trigger when I switch to **armed_home**.
I see the **panel status code** change from **Disarmed** to **Arming Home**, but it does not trigger.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/1661824/192824275-afb5c6db-a3d1-4c29-90e0-01b14bc71308.png">

Gr. Remco

**Comment by rhannink** [comment]
I also tried the following automation to detect the arming mode, but this does not trigger either. According to the documentation **Panel Status Code** should container an integer **1** or **2** during arming/pending.

![image](https://user-images.githubusercontent.com/1661824/192998644-8ad2321c-57d3-4710-b302-20355abf8084.png)

Gr. Remco

**Comment by davesmeghead** [comment]
Hi,
I have just created a new release but I have not yet released it using HACS so if you're able to download the code as a zip file and install it manually to try it that would be good if you can provide any feedback.

**Comment by rhannink** [comment]
Thanks,

I will install it manually ASAP and let you know. Thanks for the fast response.

Gr. Remco

**Comment by rhannink** [comment]
I manually installed the new release (0.8.2.0) and it looks like it is working ok. Both **arming_away** and **arming_home** now trigger my automations.

Thanks again.

**Comment by davesmeghead** [comment]
Can you update to the version released today and let me know if it's OK please? It's released here on githuc and through HACS.

**Comment by rhannink** [comment]
Hello,

Just installed the latest version via HACS (8.2.3 and 8.2.4) and everything still works fine.
Thanks for your great support.

Gr. Remco

**Comment by davesmeghead** [comment]
OK thanks
