### ISSUE TITLE
Unstable integration

### ISSUE THREAD

**Issue by martinta89** [davesmeghead/visonic#67]
Hi Dave

On the positive note, i haven't seen the 4 digit pin issue since the last update, however it still shows up in the log.

But since that update the stability of the integration to the panel has suffered heavily, and it's now failing to communicate 1-3 times per day. 

I can see that the log mentiones that it doesen't receive data from the panel, but i just have a hard time blaming the panel since the connectivity always get's established immidiatly after reloading the integration. Do you have any suggestions?

```
Expired ********************************
2022-11-03 03:03:57.977 DEBUG (MainThread) [custom_components.visonic.pyvisonic] [_clearList] Setting queue empty
2022-11-03 03:03:57.980 DEBUG (MainThread) [custom_components.visonic.pyvisonic] [sendPdu] Resetting expected response counter, it got to 0   Response list length before 0  after 2
2022-11-03 03:03:57.983 DEBUG (MainThread) [custom_components.visonic.pyvisonic] [sendPdu] Sending Command (Getting Status)    raw data 0d a2 00 00 00 00 00 00 00 00 00 00 43 1a 0a    waiting for message response ['0XA5', '0X2']
2022-11-03 03:04:03.989 ERROR (MainThread) [custom_components.visonic.pyvisonic] [Controller] Visonic Plugin has suspended all operations, there is a problem with the communication with the panel (i.e. data has not been received from the panel in 0:04:00.713791 seconds)
2022-11-03 03:04:03.992 DEBUG (MainThread) [custom_components.visonic.client] Visonic update event panel=0  event=10 {'state': 'DisConnected', 'condition': 10}
2022-11-03 03:04:04.017 DEBUG (SyncWorker_23) [custom_components.visonic.client] isPanelConnected: code format none as armcode is none (panel starting up or is there a problem?)
2022-11-03 03:04:04.020 DEBUG (MainThread) [custom_components.visonic.client] isPanelConnected: code format none as armcode is none (panel starting up or is there a problem?)
```

https://pastebin.com/ifTRuVjk

**Comment by goldazor** [comment]
Hi Dave - i just wanted to provide another log - my panel was non-responsive to a command to disarm from HA - i had to send it couple of times for it to register - nor did it record the triggering of the alarm - it occurs around 1411 on this log:

when i check the status of the panel in HA it shows an odd entry i haven't seen before - "PENDING"

screenshot: https://ibb.co/yBmRjc8 

Log: https://pastebin.com/ZVq3ufpm 

Just if there's anything obvious - it's been a solid as rock usually

**Comment by davesmeghead** [comment]
[goldazor](https://github.com/goldazor) - disable B0 processing, go in to the integrations page and "configure", step through the config pages to the B0 experimental processing page and disable it.

[martinta89](https://github.com/martinta89) - I'm not sure why but it is disconnecting and then reconnecting.  Are you using wifi, the most likely cause is wifi dropouts. I try to keep a permanent TCP connection between the integration and the panel, if there's no data from the panel in 4 minutes then I create an HA Event 
```
Visonic update event panel=0  event=10 {'state': 'DisConnected', 'condition': 10}
```
You can use this in an Automation to reconnect, this has been discussed in a previous post. However I suggest that you find the cause of the problem if you can rather than accepting it and doing this.

**Comment by martinta89** [comment]
Interesting enough, i have no issues with wireless or any IOT device who complain about wireless. it is located 3 meters away from the nearest AP.

But just to clarify. What happens if the integration doesen't get a reply within 4 minutes? You create the event but does it try to reconnect or determens there is an issue and stops trying?

**Comment by davesmeghead** [comment]
After starting HA, if the integration and panel have no interaction then after 30 seconds the integration stops and sends the HA event.

If the panel and integration initially communicate and after that the integration has not received data for 4 minutes then it stops and sends the HA event.  For some messages to the panel (that explicitly expect a reply from the panel), within that 4 minutes it does try other things like re-sending the message. It also sends a "restore" to the panel to trigger it to send back its status. So there are mechanisms within that 4 minutes to try to get the panel to respond. 

But after 4 minutes if all of these have not worked then it sends the HA Event and it is up to you to create an HA Automation to decide what to do, which could be to send you an email or to restart the integration. It does not restart the integration as:
- Some users were having issues where it restarts a lot and they wanted to decide what to do
- The physical connection between HA and the panel looks OK, so I assume it's a panel problem

There are mechanisms in there that do trigger a restart of the integration and they also fire an HA Event (but with different data to that above):
- Too many CRC Errors in the received data and within a defined timeframe
- The external physical connection is terminated (i.e. disconnected altogether such as a wifi router reboot)
- Sometimes the panel just repeatedly sends out the same packet, if this occurs for 10000 packets in a row
