### ISSUE TITLE
Failed to connect to Visonic Alarm

### ISSUE THREAD

**Issue by Johnyb62** [davesmeghead/visonic#68]
Apologies for raising this as an 'issue', but I don't know where else to post a request for help.  If this is incorrect please advise & remove.

My setup is as follows : Power Max Complete pannel / HA running in docker on Unraid server / ESP8266 flashed with ESP-Link
After flashing the ESP8266 & configuring it to connect to my wifi network, I make the changes to the configuration as advised on (Using NodeMCU) , disabling all the pins assignments (except UART pins- Normal), and turning off 'RX pull-up'

The Microcontroller console, its set to 9600 baud, Fmt:8n1. 
Connected 8266 to the powermax complete panel as per the advised pinout (reversed tx/rx):-  
![20221123_091547](https://user-images.githubusercontent.com/57109977/203758260-98164846-9e90-4cf4-9e58-d496e523e718.jpg)

It powers ok, and in the console (after entering / exiting the installer menu) see some data in the console:-
<img width="358" alt="Screenshot 2022-11-24 101723" src="https://user-images.githubusercontent.com/57109977/203758850-7fbe0852-b3ce-45a9-8546-d0495e7c261f.png">

I'm wondering if my pinout as different on this panel ?  Should I be seeing different data?  Is there a way to trace out my pinout?
I noticed the pin numbers on my board are different from those on the example:-
I have TP33/30/31/32/29/95 whereas the example has TP71/29/35/33

Any help would be much appreciated.  This is a great solution so really keen to get it working.

Error in HA:-
2022-11-24 09:36:05.739 WARNING (MainThread) [custom_components.visonic.client] Failed to connect into Visonic Alarm. Check Settings.

**Comment by davesmeghead** [comment]
It's OK to post here for specific issues yeah, for more general help it's best to post in the forum [here](https://community.home-assistant.io/t/visonic-powermax-and-powermaster-integration/316702) and you may get other users helping as well.

I must admit that I'm not familiar with using "ESP8266 flashed with ESP-Link" as another user contributed that page on the wiki. However, it does look as you you're getting something similar on the console as [here](https://github.com/davesmeghead/visonic/wiki/Using-NodeMCU-PowermaxProModel6#configuration-to-home-assistant).

I have no idea what TP numbers are used for your panel sorry, the best I can suggest is a multimeter between the pins and the pads to test for continuity (when the panel is unpowered and no battery installed of course).

What happened when you set up the integration in HA?  I need a bit more than that 1 error line, are you using the correct IP and port to set up the integration?  Also, could you please try the loopback test as [here ](https://github.com/davesmeghead/visonic/wiki#loopback-test)on the wiki.

**Comment by Johnyb62** [comment]
Yes I'm using the 8266 via Wifi.

Ok think I've cracked it.  When adding the integration in HA as well as the IP address you have to specify a port - i left it to the default as there's no indication of which port to be used in ESP-Link configuration page on the 8266.

However a quick google search came up with this..  https://github.com/jeelabs/esp-link#serial-bridge
"In order to connect through the esp-link to a microcontroller use port 23"

So setting the port number to 23 in the HA configuration solved the issue.

May be worth updating your guide page to indicate this for anyone else who uses this approach. (https://github.com/davesmeghead/visonic/wiki/Using-NodeMCU-PowermaxProModel6)

Now the basics are working I can have a play.  Brilliant integration thanks for all your hard work.
