### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by piniSolomon** [davesmeghead/visonic#7]
Hey guys,
First, let me say, great work. You made my life much happier with this component. THANK YOU. 
I updated Hass a few days ago and I started to notice that the entities of the visonic are unavailable after Hass reset. Happened twice today. BTW , resetting as mentioned in the readme fixed it. 
But, I wanted to suggest something as a future path of development. I noticed you said that while running the component independent from Hass the powerlink mode works every time, so what I was thinking is maybe to decouple the visonic from Hass and run it as standalone and communicate via mqtt with Hass ( just like sonoff or any else hardware) and as a bonus in this way you can integrate this with any other home automation platform today and in the future. 
Will be happy to hear what are your thoughts about it. 
P.S lately I realized that sonoff have auto discovery with Hass for all the available commands so it can be helpful here to discover all sensor through the stand alone service.

**Comment by davesmeghead** [comment]
Glad you like it.
There are other HA components that attempt to do what you suggest already [here](https://community.home-assistant.io/t/mqtt-smartthings-to-home-assistant-and-visonic-mct-340e-door-window-sensor/59372) so it's probably not something I'd progress. I prefer a direct connection and powerlink mode isn't necessary to get it working anyway, just a nice to have really.
I know you say that an external device could be integrated to other home automation platforms but I'm sorry to say that it's not something I'm interested in. I've tried other platforms and I've found HA to be my choice, it's not for everyone but it is for me.
Hope all goes well with your install, Kind Regards
