### ISSUE TITLE
won't connect to panel

### ISSUE THREAD

**Issue by Marrut** [davesmeghead/visonic#73]
Hi, I have a powermax pro prt (I guess it's the powermax pro part of the table on wiki). According to the wiki, it should enroll automatically. I made a setup with the wemos D1 R2. Everything is connected according to the data on wiki. (rx to tx and tx to rx) the wemos connects nicely to the network but does not want to connect to the powermax. I get the following message in the log file of the wemos.
"[W][api.connection:071]: 192.168.0.55: Socket operation failed: HANDSHAKESTATE_READ_FAILED errno=11"
can you give me a tip?

[logs_visonic_logs.txt](https://github.com/davesmeghead/visonic/files/10967308/logs_visonic_logs.txt)
[config.txt](https://github.com/davesmeghead/visonic/files/10967321/config.txt)

**Comment by davesmeghead** [comment]
This seems to be an ESP problem and nothing to do with this integration.
I googled and all I came up with is this but it might be worth you joining that thread and asking for help there
https://community.home-assistant.io/t/error-adding-esp8266-in-home-assistant-socket-operation-failed-connection-closed-errno-11/480113/17

**Comment by Marrut** [comment]
Hi, thanks in advance for your response. I'll keep looking. If it gets resolved, I'll post the solution here.

**Comment by Marrut** [comment]
Hi, I followed the link you suggested. Based on the tips that have been given, I have removed everything and added it back in homeassistant devices. After that the communication with the wemos was ok. After that I had to adjust the baud rate to 9600 instead of 38400. It works now, just some fine tuning.
thanks again.
