### ISSUE TITLE
New values for MCT-302

### ISSUE THREAD

**Issue by open1999** [davesmeghead/visonic#74]
Hello,

I try your mod, very nice job.

To complete pyvisonic.py 

**0x76** : ZoneSensorType("MCT-302", PySensorType.MAGNET ),
**0xF5** : ZoneSensorType("MCT-302", PySensorType.MAGNET ),

Thank you for this work

**Comment by davesmeghead** [comment]
Hi, do you have a PowerMax or PowerMaster?

**Comment by open1999** [comment]
Powermax.

**Comment by davesmeghead** [comment]
I've added them to version 0.8.3.0 and created a release.
