### ISSUE TITLE
Fast restar HA impossible after integration last update

### ISSUE THREAD

**Issue by Danifly80** [davesmeghead/visonic#76]
Hi,
I'm facing a problem that I think is related to the last update of the Visonic integration:
when I try to restart HA with the option "fast restart" I receive a message "name 'asyncio' is not defined"

I think is related to the Visonic integration because if I try to reload all the yaml config files, the only that fails is "visonic intruder allarm" with the same message.

anyway the integration works as expected

thanks for the help

**Comment by davesmeghead** [comment]
OK you got me :)

I've just released a bug fix 0.8.3.1 to include the asyncio import

Thanks

**Comment by Danifly80** [comment]
Thanks for the fast fix 😉
