### ISSUE TITLE
TCP connection refused -

### ISSUE THREAD

**Issue by Fitzpap** [davesmeghead/visonic#78]
Hi,

I know the IP address of the Powermaster. However I don't know what port to use? The integration defaults to 30000, I've tired this then tried 80. However in the debug logs I keep getting "connection refused"

Any ideas how I find out what port the Powermaster needs?

Thanks,

Peter

**Comment by davesmeghead** [comment]
Hi,
Let's start at the beginning.  When you say that you know the IP address of the PowerMaster, what hardware device are you using?  If you are using a Visonic Powerlink hardware device (as sold by Visonic) then this integration will not work with this hardware.  If you are not using a Visonic Powerlink hardware device and have installed your own device, according to the options on our wiki [here](https://github.com/davesmeghead/visonic/wiki#visonic-alarm-panel-for-home-assistant), then you should have set the port value yourself.

Dave

**Comment by Fitzpap** [comment]
Hi,

I have a PowerMaster30 which I have installed a PowerLink3 module inside.The PowerLink3 is connected to the LAN and its local IP address is 192.168.0.xxx. Within the PowerMaster30 menus the IP RCVR 1 is connected to an external monitoring service 062.030.222.xxx. I was hoping to connect the HA server via the IP RCVR 2. 

I build and installed the system myself several years ago. However I subscribe to an annual monitoring service so I can remotely ARM and Disarm the system and monitor the CAMs. 

I wanted to add the alarm to my HA so I can automate lights with the PIRs.

Thanks,

Peter

**Comment by davesmeghead** [comment]
Hi,
As I said, as you are using a Visonic Powerlink3 module then this integration will not work with this hardware.

However, I and another user have been experimenting, here are the links to the forum discussions:
https://community.home-assistant.io/t/visonic-powermax-and-powermaster-integration/316702/325
https://community.home-assistant.io/t/visonic-powermax-and-powermaster-integration/316702/333
https://community.home-assistant.io/t/visonic-powermax-and-powermaster-integration/316702/334
https://community.home-assistant.io/t/visonic-powermax-and-powermaster-integration/316702/337

But I must admit that he hasn't contacted me in a few months, maybe he gave up.  But I got it working to a point where:
- The Powerlink3 capability wasn't affected and works as you have it now. 
- You can also use Home Assistant "Read Only" so you can see the state of the panel and the sensors.

Whether it could do more where HA can send to the panel as well is still unknown.
If you're an electronics type person and can also help then all the information is in the 4 links above, including the Arduino code I used at the time, nothing has changed since.

Dave

**Comment by EyalRotem** [comment]
That’s actually kind of interesting to me as well.
I have a powerlink3 which I put back in the drawer but definitely prefer to use if possible.

the concept described is basically tapping into the tx/rx? Thus enabling the esp integration  and keeping the power link active?

what are the things that might not work?
I think it is something I can dabble with

**Comment by davesmeghead** [comment]
The concept is for the ESP32 to arbitrate the communications between the 3 things: the Powerlink3, the Panel and the wifi connection to HA:
- Any data that the ESP32 gets from the Panel it sends to both Powerlink3 and the HA Integration.
- It then multiplexes data from the Powerlink3 or HA to the panel.
This is what the Arduino code does.  The Integration in HA connects to the IP address / port that is set up on the ESP32 using the wifi connection.  The benefit of the ESP32 is that it has 3 UARTs, the downside is that it takes a lot of power and so I think that it cannot be powered from the power on the ribbon cable, especially as that is already powering the Powerlink3 module.

When I tried my integration in what I call "Powerlink" Mode (the Integration sends and receives the special powerlink messages to/from the panel) then the panel seemed to get confused as it was already trying to interact with a proper Powerlink3 module. So I'm pretty convinved that we won't be able to achieve Powerlink Mode from Home Assistant.

So it is likely that we will only get Standard or maybe Standard Plus Mode (if we can download the EEPROM from the Panel), these are described on the wiki [here](https://github.com/davesmeghead/visonic/wiki#the-different-connection-modes)

Dave

**Comment by EyalRotem** [comment]
Ok, I mainly use home assistant for doing stuff when arming/disarming. Maybe the door contact sensor.
So standard with override will suffice.

And during this time the app panel are connected to the internet using the powerlink3 as stock?

**Comment by davesmeghead** [comment]
To answer this:
```And during this time the app panel are connected to the internet using the powerlink3 as stock?```

This is where I admit that I do not have a provider contract that does this with a Powerlink3, that is why I created the Integration in HA. I have a Powerlink3 module that I tried this with but I could not fully test the Powerlink3 use and that it still works as stock installation.  I have a logic analyser (a really cheap device that connects to the PC via USB) and with that I could see the RS232 data in and out of the Powerlink3 just the same as without the ESP32 in the middle.  So although I can't guarantee what you ask, it does look like it should work as stock installation.

**Comment by EyalRotem** [comment]
Interesting.
Well I hope I can get to trying this. 
where can I find the arduino code?

**Comment by davesmeghead** [comment]
It's in the forum link amongst the 4 links above but here it is again:
https://community.home-assistant.io/t/visonic-powermax-and-powermaster-integration/316702/334

Like I said in the 4 forum links, buy a new ribbon cable to experiment with and cut up, and then at least you have the original to put it back :)

Dave

**Comment by EyalRotem** [comment]
Oh I thought was just a snippet, my bad.
Already placed an order for the dc converter and ribbon cable 😊

**Comment by davesmeghead** [comment]
That forum post has all the code, approx 200 lines I think, the code box has it's own scroll bar.

In the HA integration setup I suggest that you tick "Force Standard Mode" to prevent the Integration trying to achieve a Powerlink connection, like I said before this seems to confuse the panel.  If we can get this working reliably then I'll add another setup option to "Force Standard Plus Only" or maybe "I have a Powerlink3 as well" option :smiley:   

"Standard Plus" will also try to get the EEPROM data from the panel to obtain the user code and more sensor config data but let's start with forcing Standard Mode.

If you give it a try please keep me updated as to how you get on with it.
Dave

**Comment by Fitzpap** [comment]
> Hi,
> 
> As I said, as you are using a Visonic Powerlink3 module then this integration will not work with this hardware.
> 
> 
> 
> However, I and another user have been experimenting, here are the links to the forum discussions:
> 
> https://community.home-assistant.io/t/visonic-powermax-and-powermaster-integration/316702/325
> 
> https://community.home-assistant.io/t/visonic-powermax-and-powermaster-integration/316702/333
> 
> https://community.home-assistant.io/t/visonic-powermax-and-powermaster-integration/316702/334
> 
> https://community.home-assistant.io/t/visonic-powermax-and-powermaster-integration/316702/337
> 
> 
> 
> But I must admit that he hasn't contacted me in a few months, maybe he gave up.  But I got it working to a point where:
> 
> - The Powerlink3 capability wasn't affected and works as you have it now. 
> 
> - You can also use Home Assistant "Read Only" so you can see the state of the panel and the sensors.
> 
> 
> 
> Whether it could do more where HA can send to the panel as well is still unknown.
> 
> If you're an electronics type person and can also help then all the information is in the 4 links above, including the Arduino code I used at the time, nothing has changed since.
> 
> 
> 
> Dave
> 
> 

Hi, thanks for the detailed reply. I will have to do some bed time reading. I not a coder, more of a cut and paste or find and replace guy! I take my hat off to the skills demonstrated on this forum. 

Thanks for sharing your work.

Peter

**Comment by davesmeghead** [comment]
To you both, I'll close this Issue but if either of you get anywhere with this idea then please start a new Issue with an appropriate title and tag it as a new develpment feature
