### ISSUE TITLE
Integration with PowerMax Pro doesn't work with the latest versions

### ISSUE THREAD

**Issue by Joao-Sousa-71** [davesmeghead/visonic#79]
Having using this awesome integration for a while and for the first time has stoped working with an upgrade. The last version that works is the  0.8.2.4.
I'm glad to provide any information like logs etc. Just let me know what you need.

Here is the information about the setup:
Home Assistant Version: 2023.4.6
Visonic Powermax Pro with USR-TCP232
Panel Mode: Standard Plus
Protocol Version: 1.0.17.2
Panel Eprom: J-700358 v4.4.19
Panel Software: JS700550 v4.4.20
Client Version: 0.8.2.4

**Comment by EyalRotem** [comment]
To help Dave help you, you should upload a log after setting up the configuration.y’all file as shown [here](https://github.com/davesmeghead/visonic/wiki#logger-settings) 

also, you should also note what HW are you using, a d1mini? If so, make sure you use the latest firmware code from [here](https://github.com/davesmeghead/visonic/wiki/Using-Wemos-and-ESPHome#getting-the-2-files-you-need)

**Comment by davesmeghead** [comment]
As said, I would need the Home Assistant log file with the logger settings as per the wiki [here](https://github.com/davesmeghead/visonic/wiki#logger-settings).

In general it's interesting that some people seem to be having problems upgrading from 0.8.2.4 as this is the last release that uses version 0.4 of the pyserial_asyncio pypi library. I updated the code to use version 0.6 of pyserial_asyncio after this and I'm wondering if this is the reason so many people are having this issue. 

Home Assistant should detect this (using the integrations manifest.json file) and update it's libraries accordingly. 

I suggest that instead of upgrading the integration you fully remove it and reinstall it.  I realise that this is drastic as you may lose the friendly names in Home Assistant if you've set them up, so if you want me to look at a log file first then please send a link to a log file from pastebin/dropbox and I'll take a look.

**Comment by Joao-Sousa-71** [comment]
> I suggest that instead of upgrading the integration you fully remove it and reinstall it. I realise that this is drastic...

Indeed is but I'm here to help and contibute. I have HA in Dcoker so easily I can duplicate the container and mess around :-)
What I did:
1) Remove from HACS, and Add the lastest version
2) Delete the Integration
2) Restart HA
3) Add the integration - I did this many years ago and didn't remeber the parameters so **if you can share** where the configuration is stored in the /config of HA folder it will be great because for instance I don't remember things like the dowload code that used before :-( 
4) The integration is now working again but I have a now a problem which is the following. 
![image](https://github.com/davesmeghead/visonic/assets/76400918/68e41943-5075-4895-97f8-dd443555680c)

The Panel was added as **Panel 2** and therefore the entities IDs are now like binary_sensor.visonic_p2_z01 instead binary_sensor.visonic_z01....
![image](https://github.com/davesmeghead/visonic/assets/76400918/cce3ab10-f777-479e-bfeb-03238ba19b09)
Also Notice that if I remove it and add again then it will be panel 3.....
So you if you know a away to avoid this I'll be very gratefull. Otherwise I wil have to rename the all the 57 entities

About the friendly names, even having 28 sensors, that is not an issue because I have all sensor details in the customize.yaml since the integration rarely find the model. like this:

`binary_sensor.visonic_z01:
  friendly_name: Porta Principal (Z01)
  icon: mdi:door-open
  device_class: door  
binary_sensor.visonic_z02:
  friendly_name: Janela Hall Entrada (Z02)
  icon: mdi:window-closed
  device_class: window
binary_sensor.visonic_z03:
  friendly_name: Sala de Jantar (Z03)
  icon: mdi:window-closed-variant
  device_class: window  `

Thank you very much for your support.

**Comment by davesmeghead** [comment]
When I added the auto numbering of panels for users with more than 1 panel I assumed that adding and removing Integrations from Home Assistamt worked in a particular way, which during all of my testing it did.  For some users like yourself it isn't working.

I plan to remove the auto numbering so all users have to set it manually.  We have 2 ways forward with this, please tell me which you prefer.

**The first way**
As you have a backup, until then I think that the only way to do it is to:
- Delete this Integraton from Home Assistant
- Stop Home Assistant
- Directly edit core.device_registry, core.entity_registry, core.config_entries
- Remove all Visonic entries that you do not need

**The second way**
I alter the code to remove the auto numbering, upload it here in this issue, and you can test it with me
This may take me a few days to do as I'll need to test it myself as well first

Let me know, it's on my "to do" list of fixes/changes as other users have also had problems.

**Comment by davesmeghead** [comment]
Hi,
I have looked at the second way and have made the changes to a single file, it is zipped here:
[__init__.zip](https://github.com/davesmeghead/visonic/files/11477141/__init__.zip)
Please unzip to get ```__init__.py``` and replace the existing file in custom_components/visonic
And then restart Home Assistant
Let me know if you're able to do this and if so then what results you get
Thanks
Dave

**Comment by Joao-Sousa-71** [comment]
Of course I will. try I made a clone of my setup that is ready for that. 

Anyway there is something that want to share that can be the 3rd way. Before I have the latest version working I made two attempts which: the first one I put the wrong port (30000) of the USR and the second I tforgot the download code which in my is Powermax Pro is AAAA... I know my bad :-(
So, in fact the panel #2 might be because it was the third attempt (0,1,2) and I plan to redo the procedure againsince I suspect if the integration is removed and the HA is restarted then this doesn't happen.
I will let you know the result of both tests later is the day.
Thanks!

**Comment by davesmeghead** [comment]
Ah OK, so when you setup the panel and then the configuration fails it seems that Home Assistant keeps the config data and doesn't remove it. This way it keeps a panel number in the configuraion so the automation counts it as valid.

The new ```__init__.py``` file should make panel numbering manual and removes all automation for panel numbers.  

This is the draft text I have for the wiki update

The Integration supports multiple Alarm Panels, simply configure each panel from the Integration page within Home Assistant.

In the configuration, when you first set up each Panel Integration, you set the Panel Number. The Panel Number must be unique (across all panels) otherwise Home Assistant gets confused and starts naming Entities incorrectly.  Because of this, during the start-up of Home Assistant or after you set-up a new Panel, if the Integration detects a Panel Number that has already been used it will not set up the Panel (and fail to set up the Integration). If this occurs then you will need to delete the Integration (just for that Panel) and set up the Panel again.

Please let me know your comments on it

**Comment by davesmeghead** [comment]
Another thought, the auto numbering is overkill as I expect that the number of people having more than one panel is small. Those people can manually number them, considering the number of problems that auto numbering is causing.

**Comment by Joao-Sousa-71** [comment]
> Ah OK, so when you setup the panel and then the configuration fails it seems that Home Assistant keeps the config data and doesn't remove it. This way it keeps a panel number in the configuraion so the automation counts it as valid.

Maybe it is that. After I deleted Panel 2 (which was working) and created again and got Panel 3... I will do the tests in a couple of hours an let you know.

**Comment by Joao-Sousa-71** [comment]
So here are the results:
Intallation over the Panel **3** - messed container:
1) Remove Integration
2) Replace ___init__.py
3) Restart HA
4) Add the Visonic integration
5) Configure the integration
6) **Panel 0 Created**
7) Worked like a charm - Your file fixed this crazy issue!

Repeat again what I have done before with a clean clone:
1) Delete the Integration (8.2.4)
2) Remove from HACS
3) Add with HACS the lastest version (8.4.1)
4) Restart HA
5) Add the Visonic integration
6) Configure the integration - This time with all the right parameters
7) **Panel 0 Created** - Inclusive have picked my previous custom name "Panel 0 (PowerMax Pro)"

No doubt that was the bad configurations that created the multiple Panels (and maybe not restart the HA between the attempts) however I fully agree that there will very few users with more than one panel.
Finally, I have 4 or 5 diferent sensors that the integration doesn't identify the model (show Model Unknown), if you want I can generate a log and provide a table with the models. This doesn't hurt at all because I manually set the device classe but if you want to improve the Integration I'm here to help.
Thank you very much Mate.

**Comment by davesmeghead** [comment]
Oh that's good. I'll use that init.py in the next release, and also I'll include your panel model numbers as well if you provide them.

I need this information from a debug log file
```
[Process Settings] Processing settings - panel code index 0447
[Process Settings]      i=0 :    VisonicSensorRef=0xe4   zoneInfo=0xc   ZTypeName=Interior   Chime=Off   SensorType=Motion   zoneName=Kitchen
[Process Settings]      i=1 :    VisonicSensorRef=0xe4   zoneInfo=0xc   ZTypeName=Interior   Chime=Off   SensorType=Motion   zoneName=Living room
[Process Settings]      i=2 :    VisonicSensorRef=0xd3   zoneInfo=0xc   ZTypeName=Interior   Chime=Off   SensorType=Motion   zoneName=Upstairs
[Process Settings]      i=3 :    VisonicSensorRef=0x95   zoneInfo=0x7   ZTypeName=Perimeter   Chime=Off   SensorType=Magnet   zoneName=Kitchen
[Process Settings]      i=4 :    VisonicSensorRef=0x96   zoneInfo=0x7   ZTypeName=Perimeter   Chime=Off   SensorType=Magnet   zoneName=Conservatory
[Process Settings]      i=5 :    VisonicSensorRef=0x96   zoneInfo=0x7   ZTypeName=Perimeter   Chime=Off   SensorType=Magnet   zoneName=Garage
[Process Settings]      i=6 :    VisonicSensorRef=0x96   zoneInfo=0x7   ZTypeName=Perimeter   Chime=Off   SensorType=Magnet   zoneName=Bathroom
[Process Settings]      i=28 :    VisonicSensorRef=0xff   zoneInfo=0x14   ZTypeName=Delay 1   Chime=Melody   SensorType=Wired   zoneName=Hall
[Process Settings] Adding zone devices
[Process Settings] Ready for use
================================================== Display Status ==================================================
     key 0  Sensor id=1  dname=Z01  stype=Motion   zname=Kitchen        ztypeName=Interior   ztamper=0  ztrip=0  bypass=0  lowbatt=0  status=0  tamper=0  enrolled=1  triggered=0 
     key 1  Sensor id=2  dname=Z02  stype=Motion   zname=Living room    ztypeName=Interior   ztamper=0  ztrip=0  bypass=0  lowbatt=0  status=0  tamper=0  enrolled=1  triggered=0 
     key 2  Sensor id=3  dname=Z03  stype=Motion   zname=Upstairs       ztypeName=Interior   ztamper=0  ztrip=0  bypass=0  lowbatt=0  status=0  tamper=0  enrolled=1  triggered=0 
     key 3  Sensor id=4  dname=Z04  stype=Magnet   zname=Kitchen        ztypeName=Perimeter  ztamper=0  ztrip=0  bypass=0  lowbatt=0  status=0  tamper=0  enrolled=1  triggered=0 
     key 4  Sensor id=5  dname=Z05  stype=Magnet   zname=Conservatory   ztypeName=Perimeter  ztamper=0  ztrip=0  bypass=0  lowbatt=0  status=0  tamper=0  enrolled=1  triggered=0 
     key 5  Sensor id=6  dname=Z06  stype=Magnet   zname=Garage         ztypeName=Perimeter  ztamper=0  ztrip=0  bypass=0  lowbatt=0  status=0  tamper=0  enrolled=1  triggered=0 
     key 6  Sensor id=7  dname=Z07  stype=Magnet   zname=Bathroom       ztypeName=Perimeter  ztamper=0  ztrip=0  bypass=0  lowbatt=0  status=0  tamper=0  enrolled=1  triggered=0 
     key 28 Sensor id=29 dname=Z29  stype=Wired    zname=Hall           ztypeName=Delay 1    ztamper=0  ztrip=0  bypass=0  lowbatt=0  status=0  tamper=0  enrolled=1  triggered=0 
   Model PowerMax Pro Part      PowerMaster No                     LastEvent Disarm / Unknown       Ready   No           
   Mode  Download               Status      Unknown                Armed     No                     Trouble None              AlarmStatus None        
====================================================================================================================
```

And also tell me the make and model number of the unknown sensors, e.g. Z02 is a Motion Sensor, model Next K9-85

Thanks for trying this, much appreciated

**Comment by Joao-Sousa-71** [comment]
Will do that in the next days and probably wait for the next version to do the upgrade in my production environment.
I appreciate your 1st class support. Thank you!

**Comment by Joao-Sousa-71** [comment]
> I need this information from a debug log file

Hi Dave,

Here you have.

Z01: MCT-302 (with magnetic contact)
Z02,Z03,Z04,Z06,Z07,Z08,Z10,Z11,Z12,Z13,Z14,Z15,Z16: Clip MCW (Curtain Pir Detector)
Z05: MCT302-T (with magnetic contact)
Z09,Z17: PIR NEXT MCW (PIR Detector)
Z18,Z19: MCT-425 (Smoke Detector)
Z21,Z22,Z23,Z24: MCT-550 (with Flood Sensor)
Z26: Disc MCW (Ceiling Mount PIR Detector)
Z27: MCT 427 (heat and photoelectric smoke detector)
Z28: MCX-601(Wireless Repeater)
Z29: NEXT DUO (wired)

Please not that these sensors where not purchased at the same time so you may find more that one Sensor reference for the same model... 
With the log I'm including the sensor manuals and sorry because not all are in english.

[home-assistant_Debug Log for Dave.zip](https://github.com/davesmeghead/visonic/files/11522807/home-assistant_Debug.Log.for.Dave.zip)

Thank you, Joao

**Comment by davesmeghead** [comment]
Hi and thanks for that, lots of data!

Just to explain, what I need to do is add to the following dictionary in pyvisonic.py using the ```VisonicSensorRef``` from what you give me and then describe it using ```ZoneSensorType```,  note that you need to add 1 to the "i=" number to get the zone number (although in the next release I've done this to save confusion in future)

To take an example, your Z01 gives i=0 gives VisonicSensorRef=0x86 so I've added the 0x86 row below in the code.

```
ZoneSensorType = collections.namedtuple("ZoneSensorType", 'name func' )
pmZoneSensorMax_t = {
   0x08 : ZoneSensorType("MCT-302", PySensorType.MAGNET ),         # Fabio72
   0x09 : ZoneSensorType("MCT-302", PySensorType.MAGNET ),         # Fabio72
   0x1A : ZoneSensorType("MCW-K980", PySensorType.MOTION ),        # Botap
   0x6A : ZoneSensorType("MCT-550", PySensorType.FLOOD ),          # Joao-Sousa
#   0x6D : ZoneSensorType("MCX-601", PySensorType.REPEATER ),       # Joao-Sousa   ********************* Wireless Repeater *****************************
   0x74 : ZoneSensorType("Next+ K9-85", PySensorType.MOTION ),     # christopheVia
   0x75 : ZoneSensorType("Next K9-85", PySensorType.MOTION ),      # thermostat (Visonic part number 0-3592-B, NEXT K985 DDMCW)
   0x76 : ZoneSensorType("MCT-302", PySensorType.MAGNET ),         # open1999
   0x7A : ZoneSensorType("MCT-550", PySensorType.FLOOD ),          # fguerzoni
   0x86 : ZoneSensorType("MCT-302", PySensorType.MAGNET ),         # Joao-Sousa
   0x8A : ZoneSensorType("MCT-550", PySensorType.FLOOD ),          # Joao-Sousa
   0x95 : ZoneSensorType("MCT-302", PySensorType.MAGNET ),         # me, fguerzoni
   0x96 : ZoneSensorType("MCT-302", PySensorType.MAGNET ),         # me, g4seb
   0x97 : ZoneSensorType("MCT-302", PySensorType.MAGNET ),         # christopheVia
   0x9A : ZoneSensorType("MCT-425", PySensorType.SMOKE ),          # Joao-Sousa
   0xA3 : ZoneSensorType("Disc MCW", PySensorType.MOTION ),        # Joao-Sousa
   0xB3 : ZoneSensorType("Clip MCW", PySensorType.MOTION ),        # Joao-Sousa
   0xC0 : ZoneSensorType("Next K9-85", PySensorType.MOTION ),      # g4seb
   0xC3 : ZoneSensorType("Clip MCW", PySensorType.MOTION ),        # Joao-Sousa
   0xC4 : ZoneSensorType("Clip MCW", PySensorType.MOTION ),        # Joao-Sousa
   0xD3 : ZoneSensorType("Next MCW", PySensorType.MOTION ),        # me, Joao-Sousa
   0xD5 : ZoneSensorType("Next K9", PySensorType.MOTION ),         # fguerzoni
   0xE4 : ZoneSensorType("Next MCW", PySensorType.MOTION ),        # me
   0xE5 : ZoneSensorType("Next K9-85", PySensorType.MOTION ),      # g4seb, fguerzoni
   0xF3 : ZoneSensorType("MCW-K980", PySensorType.MOTION ),        # Botap, Joao-Sousa
   0xF5 : ZoneSensorType("MCT-302", PySensorType.MAGNET ),         # open1999
   0xF9 : ZoneSensorType("MCT-100", PySensorType.MAGNET ),         # Fabio72
   0xFA : ZoneSensorType("MCT-427", PySensorType.SMOKE ),          # Joao-Sousa
   0xFF : ZoneSensorType("Wired", PySensorType.WIRED )
}

```

I have encountered a couple of problems and conflicts with sensors that I already have, as follows:
- Z05 (i=4) VisonicSensorRef=0x75   There's a conflict as thermostat has already provided me with info that says it's a Motion Sensor
- Z06 and Z08   VisonicSensorRef=0xd3  I already have that as a Next MCW PIR and I know that's correct as it's my sensor

You also missed Z25 and if you get chance I'd like it as it's unique in the list (VisonicSensorRef=0x7a) and I don't already have it.

Lastly I'd like to know whether the "Z28: MCX-601(Wireless Repeater)" has any sensors?  If I get this as a sensor should I actually exclude it from the list automatically or leave it to the user to add it to the exclude list in the Config?

Thanks again for the help.

**Comment by EyalRotem** [comment]
I too want to chime in, I never noticed it was missing sensor names/models really until this issue came up.
 
 hope this is the [part of the log](https://pastebin.com/YqJC1jnN)  needed.
Z01- Magnetic - MC-302 PG2
Z02- camera PIR - Next CAM PG2
Z03- PIR - MP-802 PG2
Z04-Z10 - Curtain - Clip PG2

**Comment by davesmeghead** [comment]
@EyalRotem - I've checked and all your sensors are already listed so if you are missing sensor names/models then let me know. The main purpose of this is to set the sensor type i.e. Magnetic, Motion, Sound, Smoke, Flood etc so I can pick the right sensor device type in Home Assistant (so it then automatically picks the correct icon).

**Comment by EyalRotem** [comment]
Well, as it stands I made all the logs, and picked up all the data for nothing, as it does pick up everything (but not always, since now after a restart everything shows whereas before it didn’t, probably eeprom download related, which sometimes the integration won’t fully sync or something)

never mind 😊

**Comment by davesmeghead** [comment]
I have removed the auto numbering of panels for users with multiple panels and added the sensors that you've told me about in the latest release 0.8.5.0.  So I'll close this Issue, if you have further problems then please open a new Issue.
Thanks for your help in sorting this and giving me the new sensor data.

**Comment by Joao-Sousa-71** [comment]
> I have encountered a couple of problems and conflicts with sensors that I already have, as follows:
> 
> * Z05 (i=4) VisonicSensorRef=0x75   There's a conflict as thermostat has already provided me with info that says it's a Motion Sensor
> * Z06 and Z08   VisonicSensorRef=0xd3  I already have that as a Next MCW PIR and I know that's correct as it's my sensor
> 
> Lastly I'd like to know whether the "Z28: MCX-601(Wireless Repeater)" has any sensors? If I get this as a sensor should I actually exclude it from the list automatically or leave it to the user to add it to the exclude list in the Config?
> 
> Thanks again for the help.

@davesmeghead , sorry for the delay in answering but I was off in the last two weeks.
Here are the answers:

1)
> * Z05 (i=4) VisonicSensorRef=0x75   There's a conflict as thermostat has already provided me with info that says it's a Motion Sensor
It is a magnetic sensor mounted in teh Garage Door and configured as Entry Delay 2 (45s)

![image](https://github.com/davesmeghead/visonic/assets/76400918/2f3cb358-cf92-4a45-a31b-ade4341a0fdc)

and these are the HA attributes:

`device name: Z05
sensor type: Motion
zone type: 5
zone name: Garage
zone type name: Delay 2
zone chime: Zone
zone tripped: 'No'
zone tamper: 'No'
device tamper: 'No'
zone open: 'No'
visonic device: 5
device_tripped: 'False'
battery_level: 100
device_armed: 'True'
last_tripped_time: '2023-06-05 14:21:37.3'
panel: 0
device_class: garage_door
friendly_name: Porta Garagem (Z05)
icon: mdi:door-open`

2)
The Z06 and Z08 no doubt they are also Clip MCW . In the log they show the reference **0xd3** and I don't understant why they do not have the Reference 0xc3 like the others from the same type but suspect they where aquired later.

![image](https://github.com/davesmeghead/visonic/assets/76400918/3c266a4e-2ca9-43f8-8366-4cba387af7b9)

3)
Z28: MCX-601(Wireless Repeater)
This is just a repeater that work as a range extender:

![image](https://github.com/davesmeghead/visonic/assets/76400918/4eac5237-e84e-437a-b4fc-49320395556c)

this is how I have it in HA:

`
device name: Z28
sensor type: Undefined 109
zone type: 0
zone name: Yard
zone type name: Non-Alarm
zone chime: 'Off'
zone tripped: 'No'
zone tamper: 'No'
device tamper: 'No'
zone open: 'No'
visonic device: 28
device_tripped: 'False'
battery_level: 100
device_armed: 'True'
last_tripped_time: null
panel: 0
device_class: problem
friendly_name: Repetidor Sinal (Z28)
icon: mdi:repeat
`
Thank you!
