### ISSUE TITLE
Fails to Disarm - Solved

### ISSUE THREAD

**Issue by skykingisepic** [davesmeghead/visonic#80]
After the last HA update, Visonic no longer Disarms from HA. Arms Home or Away fine. Allow HA to Disarm has always been checked in Config.

PowerMax+ connected via USB
Home Assistant 2023.5.3
Supervisor 2023.04.1
Operating System 10.1

**Comment by davesmeghead** [comment]
Hi,
You seem to be saying that both of these are ticked, please confirm?
![image](https://github.com/davesmeghead/visonic/assets/10319422/0c7b465c-2c0a-4f63-a0ea-e2f7fc1bc45e)
Can you check for me please.

What release of this integration are you using?

If you have both these ticked then I'm going to need a Home Assistant Log file, please set your logger settings like [this](https://github.com/davesmeghead/visonic/wiki#logger-settings) in your configuration.yaml

Please restart HA and then after a few minutes please ArmHome and then when the panel has armed, please Disarm the Panel (from HA), if that doesn't work then Disarm on the panel itself and upload the HA log file to Pastebin/Dropbox.
Thanks

**Comment by skykingisepic** [comment]
Yes both are ticked.

I reinstalled integration because the USB port changes in config when updating the HA OS and it restarts. Requires deleting then adding integration back to get the first config screen to select USB and enter the correct port. Otherwise, Visonic is not available due to incorrect USB, and you can't re-select the USB once configured without deleting and adding back in.

I don't see a way to show the integration version.

Logging set as advised, restarted HA and Armed then attempted to Disarm.

Log is at https://southernexposuretrading.com/Visonic-HA-Log.txt

**Comment by skykingisepic** [comment]
Sorry to waste your time - my error. I changed the user code so the override user code in config needed to be changed. Disarm working now.

**Comment by skykingisepic** [comment]
Solved with user code change.
