### ISSUE TITLE
Is there any way to report battery low for sensors

### ISSUE THREAD

**Issue by jdgarcia99** [davesmeghead/visonic#82]
I have a powermax plus and the integration is working perfectly

However, I could not find any way to report through the integration any low battery status for sensors. The console is telling me about the issue anytime I interact with it, but it would be interesting send any alert through automations about low battery, especially when you are out of home for long periods so you can take actions

Can it be done actually? If not, is this anytime planned in the integration?

Thanks

**Comment by davesmeghead** [comment]
Hi,
I've already answered a recent question about this on the HA Forum [here](https://community.home-assistant.io/t/visonic-powermax-and-powermaster-integration/316702/386).  The answer is that it's already an attribute of each wireless sensor (but not wired sensors).
So I'll close this issue if that's OK
Thanks
