### ISSUE TITLE
HA 2023.6 connection problem / impossible to restart

### ISSUE THREAD

**Issue by Danifly80** [davesmeghead/visonic#83]
Hi, 
I have some issues after the update to HA 2023.6.

Before the update sometimes I had problems of losing connection with my Visonic power max, but a simple reload of the integration was enough to re-establish the connection.
so I made an automation that every time the pannel become "unavailable" automatically restart the visonic integration. And everything run smoothly for month

Unfortunately with the last update of HA (6.0 / 6.1) I can't reload anymore the integration neither manually nor automatically. 
The only way to regain the contron of the pannel is to restart completely HA (full restart).

Thank for you help and support

**Comment by davesmeghead** [comment]
Hi, 
Are you able to download a zip file from github of the integration and manually install it, I've just created a bug fix in 0.8.5.2 on github if you can please try it.
Thanks

**Comment by Danifly80** [comment]
Hi,
I downloaded the files and everything seams to run smoothly!
thanks for your help :) 
just after the manual installation I installed also the HACS version and I tested it ;)
