### ISSUE TITLE
Log Warning Message - Error setting up entry Panel 0 (PowerMax Pro) for binary_sensor

### ISSUE THREAD

**Issue by Joao-Sousa-71** [davesmeghead/visonic#84]
Hi Dave,

I come back to you due an warning message that HA Logs shows (tested with 2023.4.6 and 2023.5.4).
I've deleted the integration to migrate from version 0.8.2.4 to 0.8.5.2 an dI'm getting the following error evrytime that HA starts:

`2023-06-13 17:03:25.770 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Panel 0 (PowerMax Pro) for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 169, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-06-13 17:03:25.772 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Panel 0 (PowerMax Pro) for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 112, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!`

Btw the integration is working but will be glad to provide any additional information to help on the troubleshooting.

**Comment by davesmeghead** [comment]
These 2 messages are for a single sensor that the panel thinks is already connected.  I though I'd corrected this problem but obviously not, especially if this is every time HA starts. If you want me to explore more then I need a debug log file for the first 5 or 10 minutes of startup and not just the 2 error messages. Set log settings like this in your configuration.yaml file:
https://github.com/davesmeghead/visonic/wiki#logger-settings

The alternative is that you delete the integration and then stop HA running.  You then manually edit the HA entity config files to make sure all references to visonic have been removed. Are you confident to do this?  The files are in the .storage directory:
core.entity_registry
core.device_registry
If you leave core.config_entries as is then it should use these as the default settings when you setup the integration again.

**Comment by Joao-Sousa-71** [comment]
> Are you confident to do this?

Well I am and I can try it. I took a look to those files already and didn’t found nothing odd (I was expecting a double entry or something similar). 
in parallel I will generate a log to provide you of course prior to do that change .
Btw. After the update I saw some invalid Pin message as well a communication lost but want to be sure before raise any issue.
Thank you for your outstanding support.

**Comment by Joao-Sousa-71** [comment]
Hi Dave, here you have the log:

[home-assistant_Debug Log for Dave 14062023.zip](https://github.com/davesmeghead/visonic/files/11745365/home-assistant_Debug.Log.for.Dave.14062023.zip)

with this latest version I got already this twice, but i didn't have the log enabled when happened.
`2023-06-14 10:51:42.851 WARNING (MainThread) [custom_components.visonic.pyvisonic] [handle_msgtypeA7] Panel has been reset. Don't do anything and the comms might reconnect and magically continue`

I'm editing the _core.entity_registry_ and _core.device_registry_ to see how it goes.
Thank you.

**Comment by Joao-Sousa-71** [comment]
Dave,

I've remove all entries on the core.entity_registry and core.device_registry and after add the integration. As soon I finished the configuration  I got right away the same error.
`2023-06-14 13:40:56.979 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Panel 0 (PowerMax Pro) for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 169, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 179, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-06-14 13:40:56.980 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Panel 0 (PowerMax Pro) for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 112, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 179, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!`

I suspect this might be related with the sensor Z28 which is a **wireless repeater** and the latests versions ignore that device. Do you mind to rollback that change and have that device sensor available again?  That allow to check if is reachable due power failures etc. Thank you.

**Comment by davesmeghead** [comment]
Hi,
I think I've spotted the problem from your log file, thankyou, and it is related to the wireless repeater.
Can you make sure that you have the latest version of the integration from HACS/Github and then replace the pyvisonic.py file with the file in the attached zip file.  Then restart Home Assistant and let me know what happens, I'd like to see a log file whether it works or not please so I can confirm that the fix I've made is correct.  So can you capture another log file please.
Thanks
[pyvisonic.zip](https://github.com/davesmeghead/visonic/files/11750881/pyvisonic.zip)

**Comment by Joao-Sousa-71** [comment]
Dave, it fixed the issue and here you have the new log.
If it not asking too much I would prefer that you leave the wireless repeater as a manageable device it instead of ignore it because can loose power or connection etc -  Not urgent at all but in a future version.
Thank you  so much.
Joao

[home-assistant_Debug Log for Dave 15062023 with Fix Applied.zip](https://github.com/davesmeghead/visonic/files/11761070/home-assistant_Debug.Log.for.Dave.15062023.with.Fix.Applied.zip)

**Comment by davesmeghead** [comment]
Having thought about it I agree with you and I've removed that part of the code, could you please give the pyvisonic.py file a try in the zip file just to make sure. Your wireless repeater should now be shown in HA again.  I cannot associate a device type (like wired, motion etc) though as HA doesn't seem to have anything like it.
The reason that I changed my mind is there is a config setting to exclude a list of sensors in this integration and HA has the ability to disable sensors.
Anyway could you give this a try and upload a log file again. I'd like to make sure that the repeater is treat correctly in the code.
[pyvisonic.zip](https://github.com/davesmeghead/visonic/files/11761248/pyvisonic.zip)

**Comment by Joao-Sousa-71** [comment]
I just did, and it is back 👍 

![image](https://github.com/davesmeghead/visonic/assets/76400918/708b15c2-8410-4600-a1d1-0884412f3ae7)

I have it defined as "device_class: problem" which does exactly what I need.
Time to send you some cups of coffee!
Thank you again. Joao
