### ISSUE TITLE
PowerMax Pro Panel often Reset

### ISSUE THREAD

**Issue by Joao-Sousa-71** [davesmeghead/visonic#86]
Dave,

I come back to you because with the latest version of the integration I have this at least once a day:

2023-06-20 05:50:57.515 WARNING (MainThread) [custom_components.visonic.pyvisonic] [handle_msgtypeA7] Panel has been reset. Don't do anything and the comms might reconnect and magically continue

With the previous version (0.8.2.4) this working for weeks without any single reset. I do not have the log enable but I can have it until the next occurrence will happen in the case that you need. Thank you!

**Comment by davesmeghead** [comment]
Hi,
That message means that you have caused a system reset on your panel. Have you entered Installer Mode on your panel?  When you exit installer mode, the panel tells the integration that it has instigated a system reset in our panel.
So when you say you have the message once per day, are you going in to Installer Mode on the panel?

**Comment by Joao-Sousa-71** [comment]
> So when you say you have the message once per day, are you going in to Installer Mode on the panel?

No not going to installer mode. If I go then it will mode then naturally it will reset.

Just happeed again one one hour ago.

2023-06-21 10:34:19.352 WARNING (MainThread) [custom_components.visonic.pyvisonic] [handle_msgtypeA7] Panel has been reset. Don't do anything and the comms might reconnect and magically continue

As mentioned before with version 0.8.2.4 had several weeks running and this was not happen. Do you want me to enable the log?
Thanks, Joao

**Comment by davesmeghead** [comment]
A log may help but I won't know until i see it so yes please, we'll try.
I'm interested to see if it happens immediately after I send a message to the panel to see if that causes the panel to reset itself. I probably need 40 or 50 log file lines before the Warning and a few after. If you zip it up in a zip file then you can attach it to a post here.
Can you also remind me of your panel type and model e.g. Powermax Pro Part.

**Comment by Joao-Sousa-71** [comment]
> Can you also remind me of your panel type and model e.g. Powermax Pro Part.

It is  a Powermax Pro without partitions (year 2008/9)
Panel Mode: Standard Plus
Protocol Version: 1.0.20.1
Panel Eprom: J-700358 v4.4.19
Panel Software: JS700550 v4.4.20
Client Version: 0.8.5.2

[Logs with resets.zip](https://github.com/davesmeghead/visonic/files/11857235/Logs.with.resets.zip)

Here you have the logs with **two resets** that occured in less than 12 hours period. The filename has the date and time of the reset.
Thank you.

**Comment by davesmeghead** [comment]
I've had a look at the log files and they both get a system reset out of nowhere, and I have no idea why.  If you wish to stop it being a Warning in HA then I'll update the code for the next release, in the mean time you can change this line in pyvisonic.py
```
                    log.warning("[handle_msgtypeA7]          Panel has been reset. Don't do anything and the comms might reconnect and magically continue")
```
Simply change log.warning to log.info
I'm interested to know if you get the same result if you actually do a system reset on the panel.  
**_You will not lose any settings by doing this...._**
Do you have the Installer Code?
If so then get to the panel menu by entering the User Code.   Find the menu item to enter installer mode and when it asks enter the Installer Code. Now simply exit out of installer mode by pressing the disarm key on the panel, it may ask you to OK the exit and then exit the menu altogether in a similar way. 
Now have a look at the log file, at the time you exit installer mode it causes a system reset (but not a factory reset) on the panel and this should have the same result as what you are seeing in the log file.

**Comment by Joao-Sousa-71** [comment]
> I'm interested to know if you get the same result if you actually do a system reset on the panel. **_You will not lose any settings by doing this...._** Do you have the Installer Code? If so then get to the panel menu by entering the User Code. Find the menu item to enter installer mode and when it asks enter the Installer Code. Now simply exit out of installer mode by pressing the disarm key on the panel, it may ask you to OK the exit and then exit the menu altogether in a similar way. Now have a look at the log file, at the time you exit installer mode it causes a system reset (but not a factory reset) on the panel and this should have the same result as what you are seeing in the log file.

Yes, I have an installer code and when I enter in the installer mode (something that I do whenever change a sensor battery to avoid trigger a tamper) and then leave I get the same warning.
This weekend I did the upgrade to the 2023.6.3 and besides the panel reset now I'm getting these:

2023-06-26 18:42:18.328 WARNING (MainThread) [custom_components.visonic.client] Warning: Valid 4 digit PIN not found, panelmode is 1
2023-06-26 18:42:24.129 ERROR (MainThread) [custom_components.visonic.pyvisonic] ERROR Connection Lost : disconnected because the Ethernet/USB connection was externally terminated.
2023-06-26 18:42:24.131 ERROR (MainThread) [custom_components.visonic.pyvisonic] ERROR Connection Lost : disconnected due to exception [Errno 104] Connection reset by peer
2023-06-26 18:42:24.162 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for visonic doing blocking calls at custom_components/visonic/pyvisonic.py, line 1543: sleep(5.0)  # a bit of time for the watchdog timers and keep alive loops to self terminate
2023-06-26 18:42:29.163 ERROR (MainThread) [custom_components.visonic.pyvisonic] 

I need to check if it was not a network problem but have enable the log again to see if I can capture it.

The HW didn't change neither the adapter or the configuration  and I've using this integration since version 0.6.x.x and never had this kind of issues before.
After capture the next log probably I will rollback to the version 0.8.2.4 to be sure.
Keep you posted.

**Comment by Joao-Sousa-71** [comment]
And here it is the connection problem again:
![image](https://github.com/davesmeghead/visonic/assets/76400918/84640559-ae56-4eae-a94d-2300bd76c8a4)

It took less that 2 hours to happen. You have the log here - hope it helps to find waht is going on.

[home-assistant connection problem & valid 4 digit pin not found 26062023.zip](https://github.com/davesmeghead/visonic/files/11874137/home-assistant.connection.problem.valid.4.digit.pin.not.found.26062023.zip)

At 21:37 something weird happened....

This is not a great one since forces to restart HA. I'm rolling back to 0.8.2.4.

**Comment by davesmeghead** [comment]
Hi,
I've got a few quick questions and observations:
- Are you aware that you need to manually enroll in order to achieve Powerlink Mode?  You have a PowerMax Pro and as indicated [here](https://github.com/davesmeghead/visonic/wiki#supported-visonic-panels) you need to untick "auto enroll supported" and manually enroll using your panel menu. See the last bullet in that referenced section for the menu selections.  It does get to Standard Plus Mode as it gets the EEPROM data and the user code but it does not share the powerlink protocols to monitor disconnections correctly.
- On line 6140 the panel has missed a communication response and so I set the Panel Mode to "Problem".  That is why you got a ```Warning: Valid 4 digit PIN not found, panelmode is 1``` warning at 21:30:45. At 21:30:46.484 it recovers as it receives the data from the panel. 
- On line 6594 (Time 21:37:36.685) There are many sequential "Response Timer Expired" from the panel. 
- On line 6687 (Time 21:41:02.960) it is 4 minutes since receiving any data from your panel (Line 6590, Time = 21:37:02.386).  Line 6688 means that an HA Trigger event has been made in HA to inform you of this to take appropriate action should you wish to. The Integration then shuts itself down. This is the error message in your post above.
- There is not a physical disconnection, it appears that the hardware is still in place and your router has not rebooted or dicsonnected the TCP connection between HA and your panel.  It is as if the panel has just stopped sending data.  I guess that this could be a dodgy connection on the Tx/Rx wires as that would have this effect so it's something to check.

When the integration shuts itself down you could have an HA Automation to reload it and attempt to connect to your panel again.
This is not something that the integration should automate in this situation, it is a user decision to do this.

You should not need to restart HA by the way when the integration shuts itself down. Go in to settings, integrations and find the integration. Click the 3 vertical dots and select "Reload".  Like I said, you could have an HA automation do this triggered by the HA event that the integration creates i.e. ```Firing HA event, panel=0  event=10 {'state': 'disconnected', 'condition': 10, 'action': 'nopaneldata'}```.

**Comment by Joao-Sousa-71** [comment]
> * Are you aware that you need to manually enroll in order to achieve Powerlink Mode?  You have a PowerMax Pro and as indicated [here](https://github.com/davesmeghead/visonic/wiki#supported-visonic-panels) you need to untick "auto enroll supported" and manually enroll using your panel menu. See the last bullet in that referenced section for the menu selections.  It does get to Standard Plus Mode as it gets the EEPROM data and the user code but it does not share the powerlink protocols to monitor disconnections correctly.

Dave, I've never did a manual enroll in the past since I'm using the Standard Plus mode which is enough for my needs.

![image](https://github.com/davesmeghead/visonic/assets/76400918/fefec253-4f94-4982-8884-2cdafdf906d8)

Is there any change that now requires to do so?

I've just rollback to 0.8.2.4 versoin to be sure that nothing has change (also in HA)... and it is stable again. If it works for a week then we return to the tests. this last weekend had two resets per day and teh conection problems started after the upgrade to the 2023.6.3 or might be a coincidence.

> You should not need to restart HA by the way when the integration shuts itself down. Go in to settings, integrations and find the integration. Click the 3 vertical dots and select "Reload". Like I said, you could have an HA automation do this triggered by the HA event that the integration creates i.e. `Firing HA event, panel=0 event=10 {'state': 'disconnected', 'condition': 10, 'action': 'nopaneldata'}`.

I thought an automation to restart HA but that is even more simple.
Thank you.

**Comment by davesmeghead** [comment]
If you're happy with Standard Plus then that's OK still. I just found it unusual not to take that extra step and enroll the integration as powerlink mode to your panel.

If it happens more than once per day then I'd be interested in a log file from the older version to see in the log file what it might be doing differently, can you provide a 24 hour log file please from the older integration version that you thing works OK.  You don't need to stop HA, just copy/paste the log file and then use the copy.

**Comment by Joao-Sousa-71** [comment]
Dave,

I didn't came back to you because I'm trying to make a exaustive troubleshooting to avoid misleading you.
What I've found so far and the findings that still need somehow confirmation.
a) The communication problem seems to stop... 
  i) no problem found on the USR232 or wiring
  ii) no problem found on the Ethernet switch or cabling 
  But there is something that happenen that might be linked. I have a GSM module with a prepaid SIM card that went out of balance last weekend, and because of that the alarm was not able to register it in the mobile network. After rolling back to 0.8.2.4 version still had one connection problem and after charge the SIM card ( got the event GSM communication restored) by coincidence or not... HA didn't lost the connection again (almost 48 hours already). If happens I have now an automation that notify me and reload the config.

b) I still have a one or two resets per day also with the 0.8.2.4 and I start to suspect of HA since that started with the update to 2023.5.4 and didn't improve with 2023.6.3

I will keep the system running "as is" until the weekend and if nothing different show up will install the 0.8.5.2 again to see if there are changes. 

Finally, I can try the manual enroll/powerlink in the near future but wanted to have the setup stable since this is probably the most reliable integration that I had before and was not expecting this.

Keep you posted.
Thank you, Joao

**Comment by Joao-Sousa-71** [comment]
Dave,

After one week without any communication issue, today I've installed the lastest version (0.8.5.2) with the pyvisonic.py that you kindly modified. Since I'm using the Standard Plus mode, this time in the configuration wizard i didn't tick the following:

![image](https://github.com/davesmeghead/visonic/assets/76400918/81564f0b-58b5-41d5-9c93-66d597d2764b)

 Let's see how it goes in the next days.
Thank you, Joao

**Comment by Joao-Sousa-71** [comment]
Dave,
So far the comunications problems **didn't ocurred again** which are great news I think.
I continue to have some panel resets which I cannot find any pattern.... but either have 20 hours without any and then occur twice in 2 or 3 hours and sometimes during the night or even when nobody is at home.
I'm not fully sure that the resets are linked with the integration itself but the only way I can figure is to disable it for a few days and go check the panel log from time to time though the central interface to see if they stay logged.
I can also try the manual enroll to activate to enale the powerlink mode if you think that make sense to try.
If not and there are not other ideas I guess we can close this issue. 
Thank you.

**Comment by davesmeghead** [comment]
OK, thanks for the update

**Comment by Joao-Sousa-71** [comment]
Hi Dave, hope you are well.
The resets are not related with the integration and therefore I'm closing this issue.
My Alarm central seems that had better days and I'm now sure that it is a HW issue... I will exchange for a R2 version in the next weeks.
Thank you very much.
