### ISSUE TITLE
Manual Enroll

### ISSUE THREAD

**Issue by de-Bat** [davesmeghead/visonic#87]
Hi,
I have a powermax+ panel and trying to do the manual enrollment sequence.
However, when  trying to enter Installer Mode , I am asked for installer code. I don't have it...
Is there something I can do?
Thanks,
Ron

**Comment by davesmeghead** [comment]
Hi,
After you start HA with the Integration, does it get to "Standard Plus" Mode?  In other words, have you got the hardware setup and does it download the EEPROM data from the panel.?
D

**Comment by de-Bat** [comment]
Honestly, I am struggling with that, too...
I saw one time in the home assistant log some lines with the string [data receiver] and I thought I need to do an enrollment. I now understand I should see the panel status should 
change.
Currently, the integration can no connect to the panel.
I am using usr-wifi232-d2

Ron

**Comment by de-Bat** [comment]
OK. Some exciting news...
The logs shows that it is in STANDARD mode. It prints the various sensor periodically. Should I do the enrollment?

**Comment by davesmeghead** [comment]
Hi, it's good news that it gets to Standard Mode as it looks like you have the hardware set up correctly and the software installed.  We need to get it to "Standard Plus" and to download the EEPROM data before you can enroll it to Powerlink Mode.  So I'm wondering why it doesn't get to Standard Plus mode.  Have you ticked "Force Standard" in the configuration when you set up the integration?  If not then we need to work out why it doesn't get to Standard Plus mode so set the logger settings as per the wiki and load up a HA log file here and I'll take a look through.  Getting it to Standard Plus will have downloaded the Installer Code in the EPROM so we can extract the installer code for your panel, this will allow you to enter Installer Menu on the panel to enroll it in Powerlink Mode.
:)

**Comment by de-Bat** [comment]
Hi, 
Thanks,  It worked!!!
well, getting to STANDARD plus mode :)
I thought I saw the installer code and tried enrolling the panel using that code but I failed.
currently, 
- it looks like it loops and prints he various sensors
- - it displays more data than before (standard mode)
should I still do the enrolment?
How can i get the installer code?

The following lines keep repeating:

.```

```
..[sendPdu] Resetting expected response counter, it got to 25   Response list is now 1
...[sendPdu] Sending Command (I'm Alive Message To Panel)    raw data 0d ab 0...--------------...   waiting for message response ['0X2']
...[data receiver] msgType 0X2 got it so removed from list, list is now []
...[data receiver] msgType 0X2 resetting expected response counter, it got up to 0
...[handle_msgtype02] Ack Received  data = 43 
...[handle_msgtype02]    Received a powerlink acknowledge, I am in STANDARD_PLUS mode
...[sendPdu] Resetting expected response counter, it got to 25   Response list is now 2
... [sendPdu] Sending Command (Getting Status)    raw data 0d ...--------------..    waiting for message response ['0XA5', '0X2']
...[data receiver] msgType 0X2 got it so removed from list, list is now ['0XA5']
...[handle_msgtype02] Ack Received  data = 43 
...[handle_msgtype02]    Received a powerlink acknowledge, I am in STANDARD_PLUS mode
... [data receiver] msgType 0XA5 got it so removed from list, list is now []
...  [data receiver] msgType 0XA5 resetting expected response counter, it got up to 0
```

```


Thanks a lot,
Ron

**Comment by davesmeghead** [comment]
OK, so now that you get to Standard Plus Mode you are downloading the EPROM from the panel.

Can you edit pyvisonic.py
it is un the custom_components/visonic directory
If so then at approx line 2743 (depending on which version you are using), you will see these commented out lines.  A # denotes a comment in the python language.

```
                #setting = self._readEPROMSettings(pmDownloadItem_t["MSG_DL_INSTPIN"])
                #log.debug("[Process Settings]      Installer Code {0}".format(self._toString(setting)))
```
Change them to be this, ie. "debug" to "warning" and remove the #70 
```
                setting = self._readEPROMSettings(pmDownloadItem_t["MSG_DL_INSTPIN"])
                log.warning("[Process Settings]      Installer Code {0}".format(self._toString(setting)))
```
Reload the Integration (there's no need to restart HA), select the 3 vertical dots on the integration and select Reload.
You will get a Warning in Home Assistant that will tell you your Installer Code.
Remember to undo what you just did and put the code back to how it was :)

Let me know if this works and you get your installer code.

**Comment by de-Bat** [comment]
Hi,
As in previous suggestions: I worked! I got to Powerlink mode :)
Still I had some issues: 
- After restart it returned to STANDARD mode 
- There were some exceptions. (some were my mistake because the code undo was done right) 

I than removed the devices (I think during download mode) and the panel stated it has communication error.

Today I tried to start the process from a fresh start: 
- ReInstalled the integration 
- Add the device. 
It worked and I am in PowerLink mode and the Panel does not complain about errors.
Do I need o the an enrolmment?
Ron

**Comment by davesmeghead** [comment]
Oh that's good.  There's no need to do enrollment if it's in Powerlink, I would guess that there's been a Powerlink module in that panel before and so it's already recognised the Powerlink protocols.  I noticed in your previous post about Standard Plus that the panel was already sending Powerlink Acknowledges so I did think that it might just work.
Did you get your Installer Code OK?

**Comment by de-Bat** [comment]
Yes, the code change did log the correct code. Thanks.
So, last question ( hopefully) should I change the keep alive and status check intervals in order to reduce network traffic and HA performance or just stay with the defaults.?
Thanks
Ron

**Comment by davesmeghead** [comment]
Please don't change the intervals, this is where I add my disclaimer, if you start messing with the timings then you do so at your own risk. Older panels such as yours rely on the sequence and timings of the messages. Overall this causes very little network traffic and they maintain the connection between panel and HA.

You can only influence the Mode by the "Force Standard" configuration setting.  When it gets to Standard Plus Mode it has already got the EPROM data from the panel so there is very little difference between that and Powerlink.  Powerlink Mode means that it is exchanging the special powerlink messages between HA and the panel. The only reason to Force Standard is if you don't trust your network or are very security minded.  See [here ](https://github.com/davesmeghead/visonic/wiki#the-different-connection-modes) on the wiki for more information.
Dave
