### ISSUE TITLE
Sabotage alarm during reboot

### ISSUE THREAD

**Issue by phoenix-blue** [davesmeghead/visonic#89]
I recently encountered a problem that I can't trace back. Whenever I need to perform a reboot due to a Home Assistant update, I receive a sabotage alarm from the central unit due to a Powerlink error. Does anyone have an idea where this issue might be coming from?"

**Comment by EyalRotem** [comment]
I’m sure Dave will, but in the meantime- I think you should write down your setup as detailed as possible to help diagnose the issue.

**Comment by phoenix-blue** [comment]
Yes, my mistake, it's not entirely irrelevant. I have the following configuration: Visonic Powermax Pro (Nuon version) with a serial connection (RS232) directly connected to my Home Assistant environment running on Proxmox. Both the Home Assistant environment and the plugin are up-to-date with the latest versions.

Remember that I have a few weeks ago use the manual enrol option (installer mode menu 7) maybe I have done here something not right?

**Comment by davesmeghead** [comment]
What do you run Home Assistant on i.e. what hardware.  How long does it take to restart?
It looks like when you restart HA the panel things that the Powerlink module has been disconnected and that triggers an alarm. My integration pretends to be a powerlink module by mimicing the comunication. If that communication stops then the panel things it's sabotage.
This is just my guess.
Can you go in to your settings on the panel and stop this happening?  It is probably a powerlink setting or maybe a communication setting.

**Comment by phoenix-blue** [comment]
I'm running it on an NUC i7 with 16gb ram, 8gb for HS because it's running inside Proxmox.
The RS232 interface is an USB/rs232 cable.

Restart of HS is max 30 sec and I think within an extra 30 sec al the modules are loaded.

Not sure if the connection between the Powermax and HS is disturbed when I turn of the Powerlink module inside the alarm system or that I functions missed.
But I have now turned off the Powerlink module and can now made an restart of HS without sabotage alarm.

**Comment by davesmeghead** [comment]
Hi,
Can you please explain what you mean by "But I have now turned off the Powerlink module".

**Comment by davesmeghead** [comment]
Is this still a problem?  If not then I'd like to close the issue.

**Comment by davesmeghead** [comment]
Hi,
I'll close this issue, if there are problems in future then please create another issue, thanks
