### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by piniSolomon** [davesmeghead/visonic#9]
hi, until recently I ran my homeassistant on windows machine. Now I have RPI 3 b+ I'm running raspbian and trying the set the visonic component, until now I had no success.
I tried the latest hass and now I'm running on 0.89.2. 
this is the exception I'm getting
```
traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/setup.py", line 154, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
AttributeError: module 'custom_components.visonic' has no attribute 'setup'
```

so I have two questions,
1. did you try this component on hass running on RPI?
2. Can you tell what seems to be the  meaning of this error?

thank you

**Comment by davesmeghead** [comment]
The latest version of the Component will only run on HA versions 0.90 and later as the directory structure was changed by the HA developers. Please update your HA version. and make sure that the Component is unzipped in the custom_components directory

**Comment by piniSolomon** [comment]
> ...I tried the latest hass...
The problem began while running the latest hass 0.92.2. I'm getting the same error in this version as well.
I will try the specific version 0.90 and let you know.
thank you

**Comment by piniSolomon** [comment]
OK it's working now.
apparently the latest python for RPI is 3.5.3 and home assistant components wants 3.7, so after manually installing python 3.7.3 on my RPI everything worked.
thank you
