### ISSUE TITLE
remote programming

### ISSUE THREAD

**Issue by de-Bat** [davesmeghead/visonic#90]
Hi,
Can u please elaborate more regarding the support for remote programming?
I'm trying to set it up and not quite understood how to use the com0com tool and then I am failing to the bridge python script.
I keep getting :
"
serial.serialutil.SerialException: could not open port '//./COMXXXX: FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
"
I am using 'USR WIFI232 D2' 
Thanks,
Ron

**Comment by davesmeghead** [comment]
Hi, I assume that you've seen and read the wiki entry [here](https://github.com/davesmeghead/visonic/wiki#powermaster-remote-programmer-bridging)

Set up a com0com pair like this, you'll need to make sure that it uses 2 free comm ports so check device manager
![image](https://github.com/davesmeghead/visonic/assets/10319422/057255a4-6ca5-46a6-861e-074021224126)

That creates 2 virtual COM ports on your Windows PC.

You then open a powershell and connect the bridge, you may need to use python or python3 as a command.
You'll also need to install the libraries first like this
pip3 install -r requirements.txt

and then run the bridge
python bridge.py -address 192.168.X.Y -port YourPort -usb COM1

Then run the Visonic Remote Programmer and login.  Set the com port to COM2 and then click login.
Remember that the first thing you need to do is click upload to retrieve the EPROM data from the panel
:)

**Comment by de-Bat** [comment]
sorry for the delay with my response
it worked!
thanks :)
