### ISSUE TITLE
Phone Alerts

### ISSUE THREAD

**Issue by de-Bat** [davesmeghead/visonic#92]
Hi, 
in the past two weeks I'm getting tamper alerts through the phone.
It can happen twice a day, or once in 3 days.
How can I determine the cause for that?
for example panel not sitting on the correct spot, contacts to the rs232 wifi modules, a rogue sensor...
I have powermax+ and use the  usr wifi232 D module
Thanks, 
Ron

**Comment by EyalRotem** [comment]
Tamper alerts are not really related to the integration as far as I know-
In my powermax 10 it’s a contact with a spring that once the case is physically opened -than the tamper alert pops up.

check to see if everything is seated as it should, especially if the module you installed takes some of the space there.

**Comment by de-Bat** [comment]
Thanks, I will check it
But still - is there an attribute that can hint where or what to look for?

**Comment by davesmeghead** [comment]
Hi,
Tamper Alerts through your phone implies that you're getting notifications from Home Assistant.  The only way to get notifications in Home Assistant is where you asked for them in the configuration of the integration, in this setting:
![image](https://github.com/davesmeghead/visonic/assets/10319422/b96b6b75-9de7-43ed-b236-99fbcb1f839a)
Do you have the "Panel Tamper" ticked?

If this is the case then unticking it will stop the integration sending the notifications but this still leaves the problem that you are getting Panel Tamper events in the panel.  Are you getting alerts on your panel? 

In the panel there are 2 tamper switches, EyalRotem is correct one of them is the panel open with the big spring thing. The other tamper switch is against your wall so triggers if the whole panel is pulled off the wall. I suggest that you check both of these.

**Comment by EyalRotem** [comment]
I also half read a manual and some end devices have tamper switches as well, so if one was opened or in the weather and sorts, maybe it can be the culprit.
Better check the full message at the panel to be sure

**Comment by de-Bat** [comment]
.
