### ISSUE TITLE
Alarm panel not triggered

### ISSUE THREAD

**Issue by marcolega** [davesmeghead/visonic#93]
Hi I have a powermax+ uk configured in Powerlink mode, everthing seem working fine but when the system is armed and a sensor trigger, the alarm_control_panel entity does not trigger and do not indicate any alarm. Parameter "list of triggers for the siren" is set to Intruder.
The panel attribute are:
Panel Alarm Event: 'Yes'
Panel Siren Active: false
Alarm Cancel Time: 1 Minute
Abort Time: None
Panel Alarm Status: Intruder
 
I think the trigger status of panel entity is related to the status of siren, is it possible to set the entity to triggered when the Panel Alarm Event is Yes ?

This is the event:
event_type: visonic_alarm_panel_state_update
data:
  Zone: 1
  Entity: binary_sensor.visonic_z01
  Tamper: false
  Siren: false
  Reset: false
  Time: "2023-09-04T21:31:19.516901"
  Count: 2
  Type:
    - 17
    - 1
  Event:
    - 1
    - 1
  Mode:
    - Interior Restore
    - Interior Alarm
  Name:
    - Zone 01
    - Zone 01
  condition: 2
  action: panelupdate
  panel: 0
origin: LOCAL
time_fired: "2023-09-04T19:31:19.524803+00:00"
context:
  id: 01H9GTV4B4TBJVBKC9GK704ZCF
  parent_id: null
  user_id: null

**Comment by davesmeghead** [comment]
Hi, 
Please provide a log file with the settings as [here ](https://github.com/davesmeghead/visonic/wiki#logger-settings) on the wiki. 
Restart Home Assistant, Arm your system, trigger the alarm, make sure that the siren is sounding, and then Disarm. Save the log file, zip it and attach it to your post here.

**Comment by marcolega** [comment]
Attaced the log file. 
The trigger was arround 14:10 on panel 0 (I have two panel). The internal siren was sounding, but the external one (wireless) not because it have probably the battery dead.

[home-assistant.zip](https://github.com/davesmeghead/visonic/files/12565716/home-assistant.zip)

**Comment by davesmeghead** [comment]
Closing issue as many months old and no response.
