### ISSUE TITLE
Silent activation

### ISSUE THREAD

**Issue by de-Bat** [davesmeghead/visonic#96]
Hi,
First - I want to say what a great  integration!
Is there an option to arm in home mode silently? I mean with the voice abd beep feedback?
I saw there is a night mode - what does it mean and which model support it?
Thanks,
Ron

**Comment by davesmeghead** [comment]
Hi,
I've not found any way of doing this, I think there are menu options on the panel to configure what has and has not the piezo beeps and when the panel voice is spoken. I seem to remember something about "off when home" settings so you get the beeps for exit/entry delays and when disarming the panel from armed away but when it's disarmed it's silent. It might be worth you looking at the panel settings for this.
Regards

**Comment by de-Bat** [comment]
Hi, it looks like what I want.
Can I set it using the integration?
Thanks,
Ron

**Comment by davesmeghead** [comment]
> Can I set it using the integration?

Ah no, sorry.  That would mean writing the EEPROM settings back to the panel.  It is something that I've considered before and kind of know how to do, but if/when things go wrong then I'm the one that gets blames for breaking peoples alarm panels.

**Comment by de-Bat** [comment]
Yes, I understand completely.
Thanks for the response and info!
Ron
