### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by johansmitsnl** [davesmeghead/visonic#98]
I have a new set-up alarm with a [Visonic Powerlink 3.1 GENERIC ip module Rev A](https://www.visonic.com/Products/Wireless-Property-Protection/powerlink3-communication-modules) installed.

It gets an IP address from the router but how do I need to configure it to accept the connection? I have checked with `nmap` and all ports are closed.

Since I installed the alarm myself I hope you can give me some pointers here. The alarm is in normal operation.

**Comment by EyalRotem** [comment]
Please have a read at:
https://github.com/davesmeghead/visonic/wiki/Hardware-Setup

As this integration needs to use the on board connection with another device *instead* of the powerlink adapter.

**Comment by johansmitsnl** [comment]
@EyalRotem thanks for the quick reply. So I don't need the Visonic Ethernet module. I will try the RS232 connection to the board directly.

**Comment by EyalRotem** [comment]
With that method you’ll have to connect directly to the home assistant machine. 
I had great experience with  an esp device that connects to home assistant through WiFi.

**Comment by johansmitsnl** [comment]
@EyalRotem good to know. By the alarm is only 1 meter from ha and i have a cable to my disposal. If i need assistance I'll reach out.
